### ISSUE TITLE
Excessive memory use crashing build process

### ISSUE THREAD

**Issue by stensonowen** [lalrpop/lalrpop#127]
I've run into an issue where a grammar that I'm confident is valid cannot be built. The grammar 

```
grammar;
pub Email  = r"\w+@\w+\.\w{2,}";
pub Secret = r"[0-9a-fA-F]{32}";
```

results in a memory usage error. It crashed with `fatal runtime error: out of memory`. The grammar isn't ambiguous. I raised the memory allocation for the vagrant box I was using to test (trying to compile on my host crashed it) from 3GB to 4, and ran it again. Building consumes all 4GB of ram and most of swap before throwing either the previous error or `error: could not exec the linker`cc`: Cannot allocate memory (os error 12)`.
Prepending "_" to a terminal so that they no longer have intersecting FIRST sets fixes the issue, but that shouldn't be an issue, right?
Running with `--verbose` yields 

```
Compiling lalr_test v0.1.0 (file:///home/vagrant/lalr_test)
     Running `/home/vagrant/lalr_test/target/debug/build/lalr_test-f35b37e39044c03b/build-script-build`
     Running `rustc src/main.rs --crate-name lalr_test --crate-type bin -g --out-dir /home/vagrant/lalr_test/target/debug --emit=dep-info,link -L dependency=/home/vagrant/lalr_test/target/debug -L dependency=/home/vagrant/lalr_test/target/debug/deps --extern lalrpop_util=/home/vagrant/lalr_test/target/debug/deps/liblalrpop_util-d1f31dd532b4d3cb.rlib`
fatal runtime error: out of memory
error: Could not compile `lalr_test`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name lalr_test --crate-type bin -g --out-dir /home/vagrant/lalr_test/target/debug --emit=dep-info,link -L dependency=/home/vagrant/lalr_test/target/debug -L dependency=/home/vagrant/lalr_test/target/debug/deps --extern lalrpop_util=/home/vagrant/lalr_test/target/debug/deps/liblalrpop_util-d1f31dd532b4d3cb.rlib` (exit code: 1)
```

Version info:
rustc: `rustc 1.10.0 (cfcb716cf 2016-07-03)`
cargo: `cargo 0.11.0-nightly (259324c 2016-05-20)`
This happens with rust stable and beta.

It seems like it might be related to Issue #32, but I don't know enough about what goes on under the hood to diagnose it.

**Comment by nikomatsakis** [comment]
Thanks for the bug report! I agree it seems likely to be an error in the regular expression handling code.

**Comment by nikomatsakis** [comment]
Hmm, this does not reproduce for me on master. Can you try upgrading to the most recently released version?

**Comment by nikomatsakis** [comment]
(And/or can you check what version you are using -- maybe in your `Cargo.lock` file?)

**Comment by stensonowen** [comment]
I initially had the problem using `lalrpop = "0.11.0"`, and the vagrant test box uses `lalrpop = "0.12.0"` (and the same version for `lalrpop-util` in both cases).

Can you be more specific as to what I should be looking for in `Cargo.lock`? 
The overview of dependencies:
```
[root]
name = "lalr_test"
version = "0.1.0"
dependencies = [
 "lalrpop 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "lalrpop-util 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)",
]
```
The lalrpop entry:
```
[[package]]
name = "lalrpop"
version = "0.12.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "atty 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "bit-set 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "bitflags 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "diff 0.1.9 (registry+https://github.com/rust-lang/crates.io-index)",
 "docopt 0.6.82 (registry+https://github.com/rust-lang/crates.io-index)",
 "itertools 0.3.25 (registry+https://github.com/rust-lang/crates.io-index)",
 "lalrpop-intern 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "lalrpop-snap 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "lalrpop-util 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "petgraph 0.1.18 (registry+https://github.com/rust-lang/crates.io-index)",
 "regex 0.1.73 (registry+https://github.com/rust-lang/crates.io-index)",
 "regex-syntax 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc-serialize 0.3.19 (registry+https://github.com/rust-lang/crates.io-index)",
 "term 0.4.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "unicode-xid 0.0.2 (registry+https://github.com/rust-lang/crates.io-index)",
]
```
The "metadata" section:
```
"checksum lalrpop 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = "ff7b1575ca8cc268def5a19fd73cea4849a56d2ade819bfe13b8eb78f8a85191"
"checksum lalrpop-intern 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = "8acc7d538f0d74e035719d2b46dd34abf919e21f69d9eacd3d33d8bb91b4be91"
"checksum lalrpop-snap 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = "40d7ede4572f90583b0bb05af8aec2dad705f865fcecf479b8ebe959b46f8435"
"checksum lalrpop-util 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = "b2af45efc901171e23793f5edb55294dfab4fe1dc70d9df9450cb8f233ffea1f"
```
Is there something specific I should be looking for?

**Comment by stensonowen** [comment]
Dump of most of the files, including the `Cargo.lock` file: [gist](https://gist.github.com/stensonowen/7e6cacb2b1f00939cd01d86484b6d117)

And the generated `cfg.rs`, if it's relevant: http://termbin.com/4pyy

**Comment by nikomatsakis** [comment]
Huh, ok. Well, it does look like you're using the most recent version. I am not sure why I don't see the problem locally. Can you try to `cargo install lalrpop` and run the executable on the input you supplied? i.e.,

```
grammar;
pub Email  = r"\w+@\w+\.\w{2,}";
pub Secret = r"[0-9a-fA-F]{32}";
```

**Comment by nikomatsakis** [comment]
(I'll also try to setup a clone of your project; maybe the problem just doesn't reproduce with the standalone lalrpop executable.)

**Comment by stensonowen** [comment]
Running `lalrpop cfg.lalrpop` works fine.  

[Here](https://dl.dropboxusercontent.com/u/23056067/crashing_page_mon.zip) is a snapshot of my main project when the issue first appeared (right after my computer crashed).
[Here](https://dl.dropboxusercontent.com/u/23056067/lalr_test.zip) is a copy of the temporary project I've been using in a vm.

I guess there's something I hadn't considered. I tried building the project two or three times, and each time it took down the computer. So I made a vagrant instance (`debian/jessie64`, same as my host) and re-installed rustup and cargo and gcc and everything. Maybe there's something I neglected to install? Maybe crashing on the host and failing to build on the vm are distinct issues? Typing it out, that seems improbable, but I guess it's an option.

**Comment by nikomatsakis** [comment]
Huh. I'm still not able to reproduce this! I haven't tried your larger project, just the "temporary" one.

**Comment by stensonowen** [comment]
Strange. I just reproduced it on a brand new `ubuntu/trusty64` vagrant box.
```
sudo apt-get update
sudo apt-get upgrade
curl https://sh.rustup.rs -sSf | sh
curl -sSf https://static.rust-lang.org/rustup.sh | sh
sudo apt-get install zip
wget https://dl.dropboxusercontent.com/u/23056067/lalr_test.zip
unzip lalr_test.zip
rm lalr_test/target/ -r
rm lalr_test/Cargo.lock 
cd lalr_test/
cargo build
```
Encounters the same error again. Maybe there's something funky going on with with my system?? I don't know. That's strange.
