### ISSUE TITLE
Compiling lalrpop in release mode fails

### ISSUE THREAD

**Issue by Pyriphlegethon** [lalrpop/lalrpop#137]
I don't even know if this belongs here, but when compiling `lalrpop-snap` in **release mode** on my Windows 10 machine I get this error:

```
EH pad must be jumped to via an unwind edge
  %cleanuppad13 = cleanuppad within none []
  br i1 %switch.lobit, label %bb149.i, label %bb23
LLVM ERROR: Broken function found, compilation aborted!
error: Could not compile `lalrpop-snap`.
```

I'm using the newest nightly: `rustc 1.13.0-nightly (3c5a0fa45 2016-08-22)`.

**Comment by nikomatsakis** [comment]
Huh! That's no good. Seems like a rust bug.

**Comment by nikomatsakis** [comment]
@Pyriphlegethon if it's easy for you, can you check with stable maybe?

**Comment by Pyriphlegethon** [comment]
It seems to only affect the msvc nightly.

| Version | Error |
| ------------- | ------------- |
| stable-x86_64-pc-windows-msvc | Works as intended |
| nightly-x86_64-pc-windows-msvc | Error |
| stable-x86_64-pc-windows-gnu | Works as intended |
| nightly-x86_64-pc-windows-gnu | Works as intended |

**Comment by Eh2406** [comment]
It has been hanging for me, at `Compiling lalrpop v0.12.0`.

Windows 10, 
\stable-x86_64-pc-windows-gnu\ or \stable-x86_64-pc-windows-msvc\
rustc 1.11.0 (9b21dcd6a 2016-08-15)

**Comment by ahmedcharles** [comment]
Does this still happen? @Pyriphlegethon

**Comment by ahmedcharles** [comment]
Closing, please reopen if this still repros.
