### ISSUE TITLE
Variable terminals

### ISSUE THREAD

**Issue by nagisa** [lalrpop/lalrpop#140]
This is something I mentioned on IRC as nice to have, but never ended filling an issue. Not anymore!

So, consider a format like CSV, which is not really comma-separated per se, but {something-configurable}-separated. Nowadays one would define CSV along the lines of:

```
pub Row = RowNoNl "\n" => ...
RowNoNl = Column "," Row => ...
```

But it seems like it would be desirable to make such a parser generic over separator (i.e. make separator a variable terminal), so not only comma-separated, but also tab-separated, space-separated, null-separated and whatnot-separated values could be parsed at a whim of the user without writing distinct parsers for each.

**Comment by willcrichton** [comment]
Would a macro suffice for your purposes?

```
Row<T> = {
  Column T Row<T> => ...
}

pub CommaRow = Row<",">;
pub TabRow = Row<"\t">;
```

**Comment by nagisa** [comment]
@willcrichton that seems better, but you still need to do something along the lines of

```
match what_end_user_desires {
     ',' => /* parse using CommaRow */,
     '\t' => /* parse using TabRow */,
      _ => panic!("Oh no, you can’t parse using that separator, even though you clearly should be able to! What now?")
}
```

---

I well understand the danger of causing ambiguities (or incompatibilities with LR(1)) in your grammar by allowing arbitrary terminal in any position, though.

**Comment by ahmedcharles** [comment]
I don't think the suggestion, as made, seems implementable.
