### ISSUE TITLE
Is ParseError::InvalidToken implemented?

### ISSUE THREAD

**Issue by flo-l** [lalrpop/lalrpop#176]
My parser always returns `ParseError::UnrecognizedToken`, but never `ParseError::InvalidToken`.

[Documentation](https://docs.rs/lalrpop-util/0.12.1/lalrpop_util/enum.ParseError.html) says

> Generated by the parser when it encounters a token (or EOF) it did not expect.

for both.

@nikomatsakis What is the difference between the two of them?

**Comment by brendanzab** [comment]
Hmm - these are the search results on the repo: https://github.com/nikomatsakis/lalrpop/search?utf8=%E2%9C%93&q=InvalidToken - not what I'm looking at though 😕

**Comment by ahmedcharles** [comment]
I suspect that this represents the situation when a token cannot be created rather than the situation where a valid token is created but is not a match for that location in the parse. I.e. it is a lexer error, not a parse error, strictly speaking.

@nikomatsakis can reopen if this isn't the case?
