### ISSUE TITLE
Try the lane-table configuration on the pascal grammar

### ISSUE THREAD

**Issue by nikomatsakis** [lalrpop/lalrpop#204]
Once #203 is done, we should test the lane-table configuration on [the pascal grammar in the repository](https://github.com/nikomatsakis/lalrpop/blob/master/doc/pascal/lalrpop/src/pascal.lalrpop). IIRC that grammar ought to be LALR(1), so we should see a much smaller set of states, I would expect.

**Comment by wieczyk** [comment]
I will handle it.

**Comment by pothos** [comment]
It's does not have a feature flag, right? So how do I turn it on?

**Comment by nikomatsakis** [comment]
@pothos you can't yet, but #203 was proposing to use an env variable for initial testing until it's ready to go (and then it will just be the only mode).

**Comment by wieczyk** [comment]
Comparison:

```
-r--r--r-- 1 wieczyk wieczyk  641461 mar 28 19:47 pascal.rs-lane
-r--r--r-- 1 wieczyk wieczyk 1886258 mar 28 19:46 pascal.rs-legacy
```

**Comment by wieczyk** [comment]
Number of states:

* `lalr` - 409
* `lane` - 409
* `legacy` - 2229

So the lane table generated similar (or identical) automaton to lalr. Nice.

**Comment by nikomatsakis** [comment]
@wieczyk very cool!

**Comment by ahmedcharles** [comment]
What's the next step here? it seems to have been tried. :)

**Comment by wieczyk** [comment]
Probably it waits for one issue related to refactor I need to finish. I will handle it at end of the week.

**Comment by nikomatsakis** [comment]
I...guess we can close it?

**Comment by ahmedcharles** [comment]
I would, but it's not really up to me? :)

**Comment by wieczyk** [comment]
Sorry for delay :-)

**Comment by ahmedcharles** [comment]
Only the creator or someone with write/push access can close it.
