### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by ruuda** [lalrpop/lalrpop#220]
There are currently two tags, but more `release-*` branches. When I wanted to build 0.13.0, a tag was the first thing I went looking for, but I could not find any. An annotated tag has a few advantages over a branch:

 * It is harder to change a tag after pushing it, than to make a branch point to a different commit.
 * Annotated tags include a release timestamp, which may be different from the commit time of the last commit.

**Comment by nikomatsakis** [comment]
I sometimes tag, I sometimes forget. To be honest, I consider it an antiquated part of process, so I'm curious: Why would you want to check out the older release? In general, if you want the released version, why not just grab the version out of crates.io?

**Comment by ruuda** [comment]
I wanted to make a local change on top of the released version. Doing a `git clone` was faster than figuring out the exact path where Cargo stores its crates. Doing a clone also has the benefit that you get a full repository, so `git diff` and `git grep` work immediately. In this particular case I did not have to do any code archaeology, but for other repositories I have had to do so.

Another thing that I use tags for regularly, is to check whether a particular commit (usually found via `git blame`) is included in a particular release.

**Comment by brendanzab** [comment]
I use tags to provide a nice set of links in the changelog (see the links at the bottom): https://raw.githubusercontent.com/brendanzab/cgmath/master/CHANGELOG.md - this is based on the suggestion from http://keepachangelog.com/en/0.3.0/

**Comment by nikomatsakis** [comment]
Seems good. I should probably add it to my publish script. To be honest, I still find making releases kind of awkward. I feel like I don't have things setup *quite* right.

**Comment by brendanzab** [comment]
Completely agree. I find most of my releases awkward... something like https://github.com/semantic-release/semantic-release for the Rust ecosystem would be neat. Alas, no free time :(

**Comment by Marwes** [comment]
https://github.com/sunng87/cargo-release might be good though last I checked it still had some things missing to make multi crate releases easy.

**Comment by Dylan-DPC** [comment]
Can help with this. Can do it manually till we find a good way of automating it

**Comment by nikomatsakis** [comment]
@Dylan-DPC that'd be great! I'd love in general to improve our release process. In any case, if you're up for going through and tagging releases, I'll add you as a maintainer in the meantime. =) I do try to make a PR or other things around the time of each release, so it *should* be pretty easy to find.

Even better, can you modify the `publish.sh` script to do it?

**Comment by ahmedcharles** [comment]
You can compare a commit against the source for a version as it exists https://docs.rs/crate/lalrpop/0.14.0/source/ (I'm sure there's a way to download the source from crates.io, but I'm not sure how.)

**Comment by ahmedcharles** [comment]
I also tagged `0.14.0`.

**Comment by Pat-Lafon** [comment]
Closing as completed
