### ISSUE TITLE
The `<>` construct should work with named inputs

### ISSUE THREAD

**Issue by wieczyk** [lalrpop/lalrpop#226]
In example below the `<>` construct should expand to `a,b`.

* example.rs

```
use std::str::FromStr;
use ast::*;

grammar;

pub Foo: usize = {
    <a:Num> <b:Num> => Foo{ <> },
};

Num: usize = <s:r"[0-9]+"> => usize::from_str(s).unwrap();
```

* ast.rs:

```
pub struct Foo {
    a : usize,
    b : usize,
}
```

**Comment by nikomatsakis** [comment]
In particular, I would expand to "each of the names defined and in order". Also, we should update the tutorial to mention this.
