### ISSUE TITLE
Warn about rustfmt

### ISSUE THREAD

**Issue by 8573** [lalrpop/lalrpop#233]
To quote myself from rust-lang-nursery/rustfmt#1399 —

> The generated file is large and, relative to the style used by
> rustfmt, densely formatted, and has many long lines, at which rustfmt
> always emits error messages about being unable to shorten them.
> rustfmt does, however, manage to format much of the file — expanding
> it from 3010 lines to 8265.

I suggest that LALRPOP's documentation advise users to instruct
rustfmt to ignore LALRPOP's generated file, by putting
`#[cfg_attr(rustfmt, rustfmt_skip)]` on the `mod` item that references
the generated file. (Adding `#![cfg_attr(rustfmt, rustfmt_skip)]`
inside the module stops rustfmt from formatting the file, but not from
complaining about the long lines.)

(I'd offer a patch, but I don't know where it would be appropriate to
insert such a warning.)

**Comment by wieczyk** [comment]
Would it be valuable to hardcode such attribute in a code generator? It looks like something which should be always added by users.

**Comment by 8573** [comment]
@wieczyk: Unless @solson's position in rust-lang-nursery/rustfmt#1399 is accepted, the attribute needs to be added on the `mod` item in human-written code, not inside the generated file, for rustfmt to truly ignore the generated file.

**Comment by nikomatsakis** [comment]
@8573 this seems like it's primarily a documentation issue, then, right? i.e., we should include in our instructions the advice to write `#[cfg_attr(rustfmt, rustfmt_skip)] mod foo`?

**Comment by 8573** [comment]
@nikomatsakis: That's what I meant, yes; apologies if I was unclear.

**Comment by 8573** [comment]
Given the updates on rust-lang-nursery/rustfmt#1399, it sounds to me like it would now be useful to have LALRPOP add the attribute at module toplevel in the generated file.
