### ISSUE TITLE
Panic if unexpected code above grammar; is encountered

### ISSUE THREAD

**Issue by nagisa** [lalrpop/lalrpop#250]
For example:

```
struct Tag(Vec<u8>);

grammar;

pub command: () = {"boo"}
```

will panic with 

```
thread 'main' panicked at 'assertion failed: expected.is_empty()', .../lalrpop-0.13.1/src/build/mod.rs:212
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by nagisa** [comment]
Okay, it seems to be caused more by the lack of `;` after the rule than anything else.

**Comment by nikomatsakis** [comment]
This is really a dup of https://github.com/nikomatsakis/lalrpop/issues/253, I think. That is, we are not expecting to accept extra tokens, but the parse table code does.

**Comment by ahmedcharles** [comment]
I'm going to close it, since the output is now:

```
x.lalrpop:1:1: 1:6 error: unexpected token: `struct`
  struct Tag(Vec<u8>);
  ~~~~~~
```
