### ISSUE TITLE
Support pub(restricted)

### ISSUE THREAD

**Issue by olivren** [lalrpop/lalrpop#256]
The lalrpop file parser allows a `fn` or a `pub fn`, but it does not allow a `pub(crate) fn`. In fact, using `pub(crate)` makes the processing of the lalrpop file panic with `thread 'main' panicked at 'assertion failed: expected.is_empty()`.

The reason I want `pub(crate)` to be supported is because I want to unit test each grammar rule independently. Rust allows unit-testing a private function only if the test function is in the same module, but with lalrpop there is no way to inject unit tests in the generated grammar module, as far as I know. So, I wrote my unit tests in a parent module, and I have to mark the rules `pub` so they can be visible. By doing so, I end up with a `dead_code` warning for each public rule when running a simple `cargo build`.

**Comment by nikomatsakis** [comment]
👍 seems like a good thing! Would likely be a good first bug, in fact. Let me try to lay out what needs to be done:

First, we have to alter the grammar for LALRPOP files. This is found in `lalrpop/lalrpop/src/parser/lrgrammar.lalrpop`. Currently the grammar [just has `"pub"?` for visibility](https://github.com/nikomatsakis/lalrpop/blob/f7d274a76a691d29a857e08b5824baa06a45ae10/lalrpop/src/parser/lrgrammar.lalrpop#L63). I think we would want to introduce a `Visibility` nonterminal like:

```
Visibility: Visibility = {
  "pub" "(" <p:Path> ")" => Visibility::PubRestricted(p),
  "pub" => Visibility::Pub,
  () => Visibility::Priv,
};
```

Naturally, for this to work, we have to introduce the `Visibility` enum type. I imagine something like this, though it may be better to combine `Pub` and `PubRestricted` into one variant:

```rust
enum Visibility {
  Priv,
  Pub,
  PubRestricted(Path),
}

impl Visibility {
  pub fn is_pub(&self) {
    match *self {
      Visibility::Priv => false,
      Visibility::Pub => true,
      Visibility::PubRestricted(..) => true,
  }
}
```

That would go into [the `grammar::parse_tree` module](https://github.com/nikomatsakis/lalrpop/blob/f7d274a76a691d29a857e08b5824baa06a45ae10/lalrpop/src/grammar/parse_tree.rs). Next we will want to change the [field `public` of `NonterminalData`] to be of type `Visibility`. At this point, if you try to compile that, you will be able to find the various places that assume `public` is a boolean and convert them to use `match` (or a helper method, perhaps) appropriately.

**Comment by nikomatsakis** [comment]
Oh, and of course we need a test. You can add sample LALRPOP files into `lalrpop-test` and then modify the `main.rs` to include them.
