### ISSUE TITLE
Macro creates invalid mod name in generates Rust source

### ISSUE THREAD

**Issue by djg** [lalrpop/lalrpop#262]
The following grammar when compiled with lalrpop 0.13.1:

```
grammar;

// Declarations
pub decs = decs_restrict<"F","T">;
pub decs_restrict<F,T>:() = {
    decs_restrict<F,T> "var",
    decs_restrict<"", T> "function" if F == "F",
    decs_restrict<F, ""> "type" if T == "T",
};
```

generates invalid code:
```
error: expected one of `;` or `{`, found `<`
   --> src/tiger.rs:509:27
    |
509 | mod __parse__decs_restrict<"", ""> {
    |                           ^ expected one of `;` or `{` here
```

**Comment by djg** [comment]
Removing `pub` from decs_restrict macro eliminates the error.

**Comment by nikomatsakis** [comment]
The "validation code" that checks nonterminals:

https://github.com/lalrpop/lalrpop/blob/5246910e7e656c56f0b77c4f8c3cf33862b1c493/lalrpop/src/normalize/prevalidate/mod.rs#L126-L143

ought to also check if they are public macros and -- if so -- generate an error. This is an eample of generating an error:

https://github.com/lalrpop/lalrpop/blob/5246910e7e656c56f0b77c4f8c3cf33862b1c493/lalrpop/src/normalize/prevalidate/mod.rs#L140-L141

You can check if they are public by accessing [`data.public`](https://github.com/lalrpop/lalrpop/blob/5246910e7e656c56f0b77c4f8c3cf33862b1c493/lalrpop/src/grammar/parse_tree.rs#L348). You can check if they are a macro by checking if [`data.args`](https://github.com/lalrpop/lalrpop/blob/5246910e7e656c56f0b77c4f8c3cf33862b1c493/lalrpop/src/grammar/parse_tree.rs#L352) is a non-empty vector.
