### ISSUE TITLE
How to implement comments?

### ISSUE THREAD

**Issue by ivandardi** [lalrpop/lalrpop#265]
Hello!

First of all, thank you for the awesome library! It's been really fun to use. :)

I have a question regarding comments: How would I go about implementing them? Would I need to make a custom lexer? Because the language I'm trying to implement has multicharacter tokens, and I'd figure it would be hard to implement the lexer because of that just to add comments. Possibly it's a setting in the `grammar;` statement of the lalrpop file and I'm not aware of it. (Speaking of which, where can I read about the `grammar;` statement and params?)

:+1:

**Comment by mfaerevaag** [comment]
Surprised this hasn't gotten more attention. Any update on your side @ivandardi ?

**Comment by brendanzab** [comment]
You'll have to implement a custom lexer. Here's an example from one of my OSS projects (currently in semi-stealth mode): https://gist.github.com/brendanzab/4c5e5e1836ecc3a46afd05ed046c695c

**Comment by nikomatsakis** [comment]
I'd really like to fix this. It's basically blocked on silly syntactic questions. Closing as dup of https://github.com/lalrpop/lalrpop/issues/14
