### ISSUE TITLE
Consider generating .rs files into OUT_DIR by default

### ISSUE THREAD

**Issue by Marwes** [lalrpop/lalrpop#280]
This is coming from two angles.

First, cargocomb can't compile crates which generate files into the source directory https://github.com/rust-lang-nursery/crater/issues/157. While this is perhaps not really LALRPOPs problem, it may be something to consider. gluon couldn't compile with cargobomb which meant a recent improvement to rustc broke an assumption that I had (erroneously) which caused tests to segfault on nightlies with that change.

Second, with the grammar.rs file in the source tree it can be off-putting for new contributors looking for the parser to find an enormous, impenetrable file.

(While the first may not be LALRPOPs problem and the second more of a hypotetical, both of these problems were actually discovered when explaining how to contribute to gluon on a meetup so I wanted to take some steps to protect against this in the future).

Both of these are solved by hiding the file away in `OUT_DIR` instead which I now do explicitly with https://github.com/gluon-lang/gluon/pull/401 but it might be a good idea to make the default.

**Comment by brendanzab** [comment]
For my meta language I'm definitely going to be output into `OUT_DIR` - it's more how cargo is meant to be used! There is a [`use_cargo_dir_conventions`](https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop/src/api/mod.rs#L64-L70) option in the `Configuration` struct, but perhaps that should be the default. 🤔

**Comment by vmx** [comment]
I would expect that the generated file is checked into the repository. Else `lalrpop` is no longer a dev-dependency, but a normal dependency.

**Comment by brendanzab** [comment]
I normally do:

```

[dependencies]
lalrpop-util = "0.13.1"

[build-dependencies]
lalrpop = "0.13.1"
```

build-dependency, not a dev-dependency

**Comment by vmx** [comment]
@brendanzab You are right, I mixed that up (I do the same). This means that even if i check in the generated file, there would still be a dependency on lalrpop.

**Comment by brendanzab** [comment]
That's correct, but it's not included in the binary. I'm not a fan of checking in generated code, so that's what I do.

**Comment by vmx** [comment]
In the current default setup, even if you check in the generated file, you'd still have a dependency on lalrpop. This makes me change my mind, so I'm now also in favour of putting the generated files into the OUT_DIR by default (together with some documentation on how to deal with it).

**Comment by brendanzab** [comment]
I now just wish it was easier for the RLS to find stuff through `include!(concat!(env!("OUT_DIR"), "/syntax/parser/grammar.rs"));`, and then allow you to click through to it! I can dream though!

**Comment by nikomatsakis** [comment]
So, I think that `OUT_DIR` is indeed where the code is *meant* to be generated. But I also think:

```
include!(concat!(env!("OUT_DIR"), "/syntax/parser/grammar.rs"))
```

is.. basically.. unacceptable. =) I wonder if we could put a macro in `lalrpop-util` for this instead (e.g., `lalrpop_mod!(foo);`).

Longer term I had hoped to convert LALRPOP into a procedural macro. I suppose we could probably use `https://github.com/dtolnay/proc-macro-hack/` for this -- cc @dtolnay, do you think that would work?

**Comment by nikomatsakis** [comment]
(Meh, maybe I'm being too much of a stickler about the `include!` stuff. But it is the sort of over the top boilerplate I always wanted LALRPOP to avoid. I am sad you have to modify build.rs at all.)

**Comment by lqd** [comment]
(possibly interesting prototype related to the "I had hoped to convert LALRPOP into a procedural macro" comment: https://github.com/dtolnay/lalrproc)

**Comment by nikomatsakis** [comment]
All right, having let this sit, I think we should switch the default for LALRPOP 0.15.0. We'd have to adjust the tutorials and things, of course, and it'd be nice to change the repo. Anybody up for it? :)

**Comment by ayosec** [comment]
I known that it is a dirty hack, but, have you considered using a custom derive to build the parser?

Maybe something like:

```rust
#[macro_use]
use lalrpop_derive::Grammar;

// ...

#[derive(Grammar)]
#[grammar(src = "foo_bar.lalrpop")]
struct FooBar;

// ...

#[test]
fn test_grammar() {
    let result = FooBar::parse("foo bar");
}
```

**Comment by nikomatsakis** [comment]
@ayosec I have, definitely. I think though that we would want to get spans on our input though so we can give better error messages -- is that possible now with custom derive? (See also https://github.com/dtolnay/lalrproc, which was cited earlier.)

**Comment by nikomatsakis** [comment]
Well, I guess that if we do something like

```rust
lalrpop_mod!(foo.lalrpop)
```

instead of what I originally intended:

```rust
lalrpop! {
}

**Comment by ayosec** [comment]
> I think though that we would want to get spans on our input though so we can give better error messages -- is that possible now with custom derive?

IIUIC, according to [RFC 1681](https://github.com/rust-lang/rfcs/blob/master/text/1681-macros-1.1.md) it is not possible:

> > ### Defining a macro
> >
> > [...]
> > 
> > All span information for the `TokenStream` structures returned by `from_source` will
> > point to the original `#[derive]` annotation. This means that error messages
> > related to struct definitions will get *worse* if they have a custom derive
> > attribute placed on them, because the entire struct's span will get folded into
> > the `#[derive]` annotation. Eventually, though, more span information will be
> > stable on the `TokenStream` type, so this is just a temporary limitation.


> > # Drawbacks
> >
> > [...]
> >
> > * Converting to a string and back loses span information, which can
> >   lead to degraded error messages. For example, currently we can make
> >   an effort to use the span of a given field when deriving code that
> >   is caused by that field, but that kind of precision will not be
> >   possible until a richer interface is available.

---

IMHO, `lalrpop! { ...  }` should wait for macros 2.0.

**Comment by nikomatsakis** [comment]
@ayosec I think we should just use the OUT_DIR for now and hold off on the "proc macro" approach until the proper thing is stabilized -- I don't think that is *so* far away. Probably this year. Would you be up for preparing a PR that converts the LALRPOP default and updates the docs and so forth?

**Comment by ayosec** [comment]
> hold off on the "proc macro" approach until the proper thing is stabilized

+1

Another issue I though after my last comment is that the hack with the derive macro can have some incompatibilities with incremental compilation: if the `.lalrpop` is modified, the compiler will not update the `.rs` where it is included. I have not tested it, though.

> Would you be up for preparing a PR that converts the LALRPOP default and updates the docs and so forth?

Yep! I can try it :)

**Comment by ayosec** [comment]
I have a WIP in [my fork](https://github.com/lalrpop/lalrpop/compare/master...ayosec:outdir-280).

There is a macro `lalrpop_mod!(foo);`. It is expanded to

```rust
lalrpop_mod!(foo, "/foo.rs");
```

Then, it is expanded to

```rust
mod foo {
    include!(concat!(env!("OUT_DIR"), "/foo.rs"));
}
```

Is this OK?

---

`cargo test` is green.

---

I guess that the next steps are:

* Add a function in `Configuration` to keep the previous behaviour.
    * What do you thing about `generate_in_source_tree` instead of `create_rs_files_in_place`?
* Update the documentation.

**Comment by nikomatsakis** [comment]
@ayosec that sounds awesome! Can you open a PR?

> What do you thing about generate_in_source_tree instead of create_rs_files_in_place?

Sounds good.

Sorry I missed the notification here for a while.

**Comment by nikomatsakis** [comment]
@ayosec ping =) any chance you could open a PR with that work?

**Comment by ayosec** [comment]
https://github.com/lalrpop/lalrpop/issues/280#issuecomment-375394916

> any chance you could open a PR with that work?

Yep!

I'm sorry. I had some heavy weeks in my regular job, so I had no time for this. I hope that I can finish the pending changes this weekend.

**Comment by ayosec** [comment]
The patch is *almost* ready. I [updated](https://github.com/lalrpop/lalrpop/commit/d1f7074d3a9474c4b9c060d73e664c273c29a702) the documentation related to the `mod` declaration, but I'm not sure if this is enough.

---

I'm thinking about adding a `pub` modifier in the `lalrpop_mod` macro, since there is no way to declare the module as public.

The old

~~~rust
pub mod parser;
~~~

will be

~~~rust
lalrpop_mod!(pub parser);
~~~
