### ISSUE TITLE
Matches do not happen if a rule has two regular expressions

### ISSUE THREAD

**Issue by JordanBoltonMN** [lalrpop/lalrpop#282]
A rule using two or more regular expressions seem to never result in a match. Given the rules:

```
pub Foobar1: () = {
    r"foobar" => ()
};

pub Foobar3: () = {
    r"foo" r"bar" => ()
};
```

The following occurs:

```
println!("{:?}", issue::parse_Foobar1("foobar")); // Ok(())
println!("{:?}", issue::parse_Foobar2("foobar")); // Err(UnrecognizedToken { token: Some((0, (4, "foobar"), 6)), expected: ["r#\"fo\"#"] })
```

See my repo https://github.com/JordanBoltonMN/lalrpop_issue which contains the code above.

OS: Windows 10
rustc: 1.21.0
cargo: 0.22.0

**Comment by vmx** [comment]
Thanks for the repo, that made it easy to try. I'm quite new to LALRPOP, but I'd say it's the expected behaviour. The default tokeniser cuts tokens at whitespaces. `r"foo" r"bar"` are two tokens, but `foobar` is only one, hence it doesn't match.

**Comment by JordanBoltonMN** [comment]
@vmx I brought the issue up to @nikomatsakis on Gitter. His response was that it was a surprising find as it should be a match in both cases, though the second case ALSO allows a match on a space.

**Comment by nikomatsakis** [comment]
@vmx is correct that this is the expected behavior. I think that the documentation around the matching behavior could be radically improved though.

**Comment by nikomatsakis** [comment]
I'm confused though. The repo seems to contain somewhat different code, and also the description is somewhat internally inconsistent (e.g., it mentions `Foobar3` and `Foobar2`)

**Comment by nikomatsakis** [comment]
Going to close this issue, in any case.
