### ISSUE TITLE
document the role of lalrpop-snap

### ISSUE THREAD

**Issue by Storyyeller** [lalrpop/lalrpop#284]
Hi, 

I've been trying to work on lalrpop, and I was wondering what lalrpop-snap does. There doesn't seem to be any documentation for it, but I figured I'd post an issue here in case Niko is watching this. More generally, an explanation of the layout of lalrpop would be helpful.

Also, are there any tricks to speed up compilation time? Right now, it takes 35 seconds for a debug compile if I edit parse_table.rs, which makes it difficult to test changes.

Edit: Looks like using nightly makes compilation much faster.

**Comment by brendanzab** [comment]
An [LALRPOP grammar](https://github.com/nikomatsakis/lalrpop/blob/01ccd43789db6f4f873a37673516b839fb04f422/lalrpop/src/parser/lrgrammar.lalrpop) is used to describe the syntax of LALRPOP, so it needs to bootstrap itself off a snapshot of the grammar. `lalrpop-snap` is that snapshot.

**Comment by nikomatsakis** [comment]
Sigh, in general, more documentation is needed. Also, we should probably update the snapshot.

**Comment by nikomatsakis** [comment]
I'm going to close this issue for now though

**Comment by nikomatsakis** [comment]
Actually, I'll keep it open as a "doc needed" bug. Not sure where such docs should live though.

**Comment by nikomatsakis** [comment]
Closing as dup of https://github.com/lalrpop/lalrpop/issues/292
