### ISSUE TITLE
create a "LALRPOP manual"

### ISSUE THREAD

**Issue by nikomatsakis** [lalrpop/lalrpop#292]
I think we should move LALRPOP documents into an [mdbook](https://github.com/rust-lang-nursery/mdBook).

Currently we have the tutorials etc living in `doc`. It'd be nicer to have an mdbook that auto-renders  to a github pages. Then we can also start adding LALRPOP internals in there in another chapter. I envision a table-of-contents sort of like:

- How to setup your project
    - roughly what the README has
- Tutorial
- Custom lexers
- Getting an error?
    - the error messages can give links in here
- Contributing and implementation details
    - high-level overview of how the code works and other stuff
    - the role of lalrpop-snap
    - maybe collect some of the material from my blog posts in some cases

**Comment by nikomatsakis** [comment]
To get started, I'd say let's just rearrange the existing things into this structure.

**Comment by udoprog** [comment]
Hey. I would like to do the initial breakout. If I don't get anything done until tonight I'd be happy if someone else took it over.

This is the first time I use mdbook (looks cool!). The example is easy enough to follow.

I'm going to try to break the existing tutorial sections into distinct pages. At the top there is a TOC, which fills the same purpose as a `SUMMARY.md`.
I'm also going to add a contributors section based of the existing contributors list on Github. It's nice to give folks some exposure on the manual page for doing good work :). I'll keep this as a separate commit if we don't want to do include this.
