### ISSUE TITLE
Extract state machine code into lalrpop-util.

### ISSUE THREAD

**Issue by ahmedcharles** [lalrpop/lalrpop#303]
I'm thinking of taking the following approach:

1. Change the generated code incrementally to use a trait/impl, such that the state machine code becomes static.
2. Move the state machine code to `lalrpop-util`.

This could be done for any code that is sufficiently generic.

**Comment by nikomatsakis** [comment]
Yes, I'd love to see this happen. I *think* this should be possible. I have to look over the code though to figure out where to start. It might be worth sketching out first what the trait should look like that LALRPOP generates.

At minimum, the trait will need:

- The symbol type, which combines the type of nonterminals etc
- The "reduce" function that executes action code

**Comment by ahmedcharles** [comment]
Given that error recovery and custom grammar parameters are a thing, I'm not sure quite how to store the parameters in a struct in a way that lets them be used the way they currently are, but perhaps I'm just missing something. Note, I haven't tried the obvious solution of just storing them in the generated struct as is and using them that way.

@nikomatsakis Any ideas?

**Comment by ahmedcharles** [comment]
Note: https://github.com/ahmedcharles/lalrpop/tree/extract has WIP changes to `lalrpop-util`.

**Comment by nikomatsakis** [comment]
I've been working on this in this branch:

https://github.com/lalrpop/lalrpop/tree/ndm-extract-state-machine

The branch adds the state machine here:

https://github.com/lalrpop/lalrpop/blob/ndm-extract-state-machine/lalrpop-util/src/state_machine.rs

Next up is to finish this function:

https://github.com/lalrpop/lalrpop/blob/ae69af4717b374dc35c5bf60894c32be15336155/lalrpop/src/lr1/codegen/parse_table.rs#L158-L246

I was considering modifying the `state_machine.rs` definition to use newtypes, as well. Right now it has a lot of `i32`, it'd be nice to have newtypes like `State(i32)` or `Action(i32)` etc.

. I think i've written up the state machine, but

**Comment by nikomatsakis** [comment]
I haven't had any time to hack on this lately -- if anyone is interested in getting involved, let me know! I can help guide you over [on gitter](https://gitter.im/lalrpop/Lobby).
