### ISSUE TITLE
Tutorial Link is broken

### ISSUE THREAD

**Issue by masonk** [lalrpop/lalrpop#305]
This link, which is referenced in the project's [readme](https://github.com/lalrpop/lalrpop), is broken:

https://github.com/lalrpop/lalrpop/blob/master/doc/tutorial.md

**Comment by nikomatsakis** [comment]
That link is no longer referenced in the README. The tutorial is now located at:

http://lalrpop.github.io/lalrpop/tutorial/index.html

Thanks!
