### ISSUE TITLE
Possible lalprop parser error

### ISSUE THREAD

**Issue by dtkerr** [lalrpop/lalrpop#307]
Hit an issue in which legal rust makes lalrpop choke during parsing the grammar definition;

Problematic grammar file used:
```
grammar;

pub StringArg: String = {
    <s:r#"'[^']*'"#> => s.chars().skip(1).take_while(|c| *c != '\'').collect(),
};
```

Causing this error:
```
processing file `test_quote.lalrpop`
... test_quote.lalrpop:7:2: 7:2 error: unexpected token: `;`
--- stderr
  };
   ^
```

But note that it's specifically the `'\''` causing the issue, because replacing the `'\''` with any other character (Even the effectively identical `'\u{0027}'`) works just fine.

**Comment by nikomatsakis** [comment]
That is probably a bug in the LALRPOP tokenizer, specifically around this code:

https://github.com/lalrpop/lalrpop/blob/d740f500ba039c8d51658e6d91d432bea1febfbf/lalrpop/src/tok/mod.rs#L481-L486

and hence probably this function:

https://github.com/lalrpop/lalrpop/blob/d740f500ba039c8d51658e6d91d432bea1febfbf/lalrpop/src/tok/mod.rs#L543-L563

It seems like we do [*try* to handle `\'` though](https://github.com/lalrpop/lalrpop/blob/d740f500ba039c8d51658e6d91d432bea1febfbf/lalrpop/src/tok/mod.rs#L549), but I guess that check isn't quite working.
