### ISSUE TITLE
Support impl trait as a return type

### ISSUE THREAD

**Issue by rusterize** [lalrpop/lalrpop#308]
How much work is required to support impl trait as a return type in the grammar? 

I know Associated Types are supported; but I would really like to see impl trait supported. This will allow very flexible language "backends" that operate under a trait without having to do a heap allocation each time!

**Comment by nikomatsakis** [comment]
@rusterize hmm, that's a good question. That's probably kind of hard until abstract types are fully supported, since we have to be able to put the types into a struct or other data structure.

**Comment by nikomatsakis** [comment]
So I'm sorry to say I don't think we can do this now. Going to close the issue for now.

**Comment by nikomatsakis** [comment]
*Actually,* it occurs to me that `impl Trait` may 'just work' using the recursive ascent mode, since then we store all the values on the stack and so forth. @rusterize have you tried that? You tag our grammar with `#[ascent]` I believe...

**Comment by rusterize** [comment]
@nikomatsakis , thank you so much for your reply, I really appreciate it. You mean something like this should work?
```rust
use grammar::MyTrait;
use grammar::Runner;

#[ascent]
grammar<R,T>(runner: &mut R) where R: Runner, T:MyTrait;

pub Script: Vec<T> = {
   (<Term> ",")+
}

Term: T = {
    <a:Something> => fun_that_returns_impl_MyTrait(a),
    <a:SomethingElse> => fun_that_returns_impl_MyTrait(a),
};

// ...definitions for Something, and SomethingElse...
```

Thanks again!
