### ISSUE TITLE
Getting the line number with each token

### ISSUE THREAD

**Issue by little-dude** [lalrpop/lalrpop#323]
Hi,

I'm following the [Standford MOOC on compilers](https://lagunita.stanford.edu/courses/Engineering/Compilers/Fall2014/22e542a9f1f648779506b78ee6881241/), but since I know Rust much better than C++ and Java, I'm trying to do the assignments in Rust.

The first one is to write a lexer for the [cool programming language](https://en.wikipedia.org/wiki/Cool_(programming_language)) using `flex`. The closest thing to `flex` in the Rust world seems to be `lalrpop`.

`lalrpop` works fine, but the lexer I'm supposed to build must *output the line on which each token has been found* (if the token spreads on multiple lines, it should be the last one). One way to solve this is to write a custom tokenizer that does _not_ ignore newlines as shown [in the tutorial](http://lalrpop.github.io/lalrpop/lexer_tutorial/index.html). But that means in my grammar, I need to handle all these newlines, which makes things _much_ more complicated.

For instance, to count lines when parsing comments I'd have to do something like this:

```rust
/// Match comments starting with "--" and ending at end of line or end of file, eg:
/// ```
///      -- this is a comment
/// ```
LineComment: u32 = {
    r"--.*\n" => 1,
    r"--.*" => 0,
};

Char: u32 = {
    "\n" => 1,
    r"." => 0,
};

CommentContent: u32 = {
    <MultiLineComment>, // handle nested comments
    <Char>,
    <n1:Char> <n2:CommentContent> => n1 + n2, // handle (* comment (* nested *) *)
    <n1:MultiLineComment> <n2:CommentContent> => n1 + n2, // handle (* (* nested 1 *) (* nested 2 *) *)
};


/// Match multiline comments, eg:
/// ```
///      (* this is also a on a single line *)
///      (*
///          this is a comment spread
///          on multiple lines
///      *)
/// ```
MultiLineComment: u32 = {
    "(**)" => 0,
    "(*" <CommentContent> "*)",
};

pub Comment: u32 = {
    <MultiLineComment>,
    <LineComment>,
};
```

Whereas parsing comment is trivial otherwise:

```rust
/// Match cool comments
pub Comment: () = {
    // match comments starting with "--" and ending at end of line or end of file, eg:
    //      -- this is a comment
    r"--.*\n", r"--.*",

    // match multiline comments, eg:
    //      (* this is also a on a single line *)
    //      (*
    //          this is a comment spread
    //          on multiple lines
    //      *)
    r"(?s)\(\*.*\*\)",

    // match nested multiline comments, eg:
    //      (* this a (* nested comment *) *)
    "(*" Comment "*)"
};
```

So is there a way to write a custom tokenizer that counts the lines for me, and somehow use that count in my grammar? For instance I'd like to be able to write something like this:

```rust
use std::str::Chars;

pub type Spanned<Token, Loc, Error> = Result<(Token, Loc), Error>;

pub struct Tokenizer<'input> {
    input: &'input str,
    line_no: usize,

}

impl<'input> Tokenizer<'input> {
    pub fn new(input: &'input str) -> Self {
        Lexer { input: Chars<'input>, line_no: 0}
    }
}

enum LexicalError {
    // not possible
}

impl<'input> Iterator for Tokenizer<'input> {
    type Item = Spanned<Token, usize, LexicalError>;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            match self.chars.next() {
                // ignore newlines, but increment the internal count
                Some('\n') => {
                    self.line_no += 1;
                    continue;
                }
                Some(c) => return Some(Ok((c, self.line_no))),
                None => return None, // End of file
            }
        }
    }
}
```

and then use the `Spanned` that is returned, in the grammar. Is it even possible? If so could someone give me some pointers?

I hope my question makes sense.

**Comment by Marwes** [comment]
If you don't need the locations during the lexing and parsing stage there is another approach which I would argue to be better.

Since LALRPOP gives you the byte offsets for each token you can translate these offsets into row (and column) locations after parsing has completed. Doing this translation only requires you to search the input string until the offset and keeping track of which line you are.

(Example: https://github.com/gluon-lang/gluon/blob/f8326d21a14b5f21d203e9c43fa5bb7f0688a74c/base/src/source.rs#L22-L35 and https://github.com/gluon-lang/gluon/blob/f8326d21a14b5f21d203e9c43fa5bb7f0688a74c/base/src/source.rs#L56-L83)

The benefit of that approach is that (usually) you only need the row information in error messages, which lets this calculation as well as the extra size needed for location be avoided in the successful path.

**Comment by little-dude** [comment]
@Marwes thanks for your answer! In the meantime, @nikomatsakis told me on gitter that what I wanted was not possible, so I started using `rust-peg`. But I'll definitely try your solution too. It would be nice to complete the assignment with both tools, to compare.

**Comment by brendanzab** [comment]
In my code for [pikelet](https://github.com/brendanzab/pikelet) I'm starting to make a crate called [codespan](https://github.com/brendanzab/codespan) for handling this. It's not yet published to crates.io, and the errors are still a little ugly, but I'll eventually see if I can convert gluon to use it. You'll be able to see where I use it [in the parse module](https://github.com/brendanzab/pikelet/tree/aee44a084d4a9be0af4bb96031e5bd0179c13192/src/syntax/parse).

**Comment by nikomatsakis** [comment]
I'm inclined to close this -- I don't think that at present there is much information needed on LALRPOP's part -- I agree with @brendanzab that it'd be nice to have a utility (perhaps something we could bring eventually into lalrpop as an optional crate, perhaps independent) that handles a lot of this stuff for you though. The approach that @Marwes outlines is indeed what I usually do.
