### ISSUE TITLE
string_cache dependency locked to a version

### ISSUE THREAD

**Issue by Dylan-DPC-zz** [lalrpop/lalrpop#368]
In #366, it was noted that:
> string_cache broke compatibility with rust < 1.23 so I locked the version to 0.7.1 which works. Could perhaps try and get a new version of string_cache but not sure it is worth the effort?

followed by: 

@matklad 
> Locking dep to a particular version can be problematic. For example, this would make LALRPOP unusable with anything which specifies string_cache = "0.7.2". I think a better solution would be to do cargo update string_cache "0.7.1" in CI for Rust 1.20.0, if we don't want to just bump the minimal Rust version.
Since it is an internal dependency it is ok to have it locked down
Unfortunately Cargo is not able to distinguish between internal and public dependencies yet, so it just flatly prohibits resolution graphs with two semver-compatible versions. That is, if crate foo has
```
[dependencies]
string_cache = "0.7.2"
lalrpop = "0.13.2" # pretend this is the new published lalrpop version with `=` or `<=` constraint
```
> then Cargo won't be able to resolve its dependencies at all.
In general, I would argue that semver open 0.7.1 is the correct constraint here, regardless of the above issue.
It is the leaf crate with Cargo.lock that ultimately decides about dependencies. If the leaf crate must be built with Rust 1.20.0, it should have string_cache = 0.7.1 in lockfile. If it is build with say, 1.25.0, it should have string_cache = 0.7.2 in the lock. The job of LALRPOP here is to be compatible with both, and not to impose additional versioning constraints.
Does this make sense? :)
There’s no consensus as to whether bumping required rustc version is a breaking change or not (discussion: rust-lang-nursery/api-guidelines#123). I personally am convinced that it is not a breaking change.

@Marwes
> @Dylan-DPC For the moment I think it is enough to just include a lockfile.

**Comment by Marwes** [comment]
It is only locked for building/testing lalrpop itself though, for users of lalrpop the lockfile is ignored.

**Comment by dkg** [comment]
fwiw, bumping the string_cache dependency to 0.8.0 seems like it would be warranted today, as that seems to be a relatively stable release from string_cache upstream.
