### ISSUE TITLE
Turn `Parser::parse(s: &'a str)` into `parse<S: AsRef<str>>(s: S)`

### ISSUE THREAD

**Issue by Mestake** [lalrpop/lalrpop#378]
It would be wonderful if created parsers get their input as `std::AsRef<str>` generic type rather than `&str` so users don't have to explicitly convert their strings into `&str` (`String::as_str` and similar)

**Comment by Marwes** [comment]
For `String` you should just be able to rely on auto deref and just write `.parse(&string)` which I think is easy enough. Using AsRef it would need to be `.parse (&*string)` as AsRef <str> is not implemented for `&String`.

**Comment by Marwes** [comment]
Thanks for the feedback but I believe this will be left as is since it is already fairly convenient to use.
