### ISSUE TITLE
`lalrpop-util = "0.15.2"` on crates.io doesn't contain `lalrpop_mod`

### ISSUE THREAD

**Issue by king6cong** [lalrpop/lalrpop#382]
macro_rules! lalrpop_mod is added in e7db1ee2e25619009df00d4a9102f4e0217aa786
PR: https://github.com/lalrpop/lalrpop/pull/353

but `lalrpop-util = "0.15.2"` on crates.io doesn't contain `lalrpop_mod`, which will result http://lalrpop.github.io/lalrpop/tutorial/002_paren_numbers.html failure:

```error: cannot find macro `lalrpop_mod!` in this scope```

change dep `lalrpop-util` to master solves the problem.

**Comment by kjetilkjeka** [comment]
This causes users following the tutorial to get a compile error at the "invoking the parser" step at this page http://lalrpop.github.io/lalrpop/tutorial/002_paren_numbers.html

**Comment by flyingP0tat0** [comment]
The tutorial is even [mentioning](http://lalrpop.github.io/lalrpop/generate_in_source.html) version 0.16. Is there any reason not to release 0.16?

**Comment by Dylan-DPC** [comment]
They weren't many changes to make a jump to 0.16. The reason it shows 0.16 in tutorials is because in one of the early PRs (either  0.15.0 or 0.15.1 was released)  assumed the next release will be 0.16.

**Comment by flyingP0tat0** [comment]
Sure, but the way it is handled in the docs right now is pretty inconsistent...

**Comment by bemeurer** [comment]
What is the fix for this? It was pretty frustrating to try and follow the tutorial to get a feel for lalrpop and then have it just plain not work.

**Comment by flyingP0tat0** [comment]
Well, you could use master until 0.16 is released.

**Comment by iamsubhranil** [comment]
why not make a hotifx and backport it to 0.15.2? The tutorial is largely frustrating and misleading at this point for new users!

**Comment by nikomatsakis** [comment]
We discussed in the meeting and decided to cut a new 0.16.0 release so that the docs will be synchronized. This isn't done yet though. =)

**Comment by tekknolagi** [comment]
Is it still broken for 0.15.2?

**Comment by Marwes** [comment]
> Probably, I've thought the bugfix was "upgrade to 0.16.0"

Yep, the only thing broken for 0.15 was that the docs was out of sync since they point to git master.
