### ISSUE TITLE
Help with "Dangling Else" problem needed

### ISSUE THREAD

**Issue by snsmac** [lalrpop/lalrpop#386]
Hello,
one of the classic Problems with LR Parsers is the [`Dangling else problem`](https://en.wikipedia.org/wiki/Dangling_else). It leads to a shift-reduce conflict.
An grammer which triggers this problem is the following:
```
grammar;
pub stmt: () = {
    expr,
    if_stmt,
}

if_stmt: () = {
     "if" expr "then" stmt,
     "if" expr "then" stmt "else" stmt,
}

expr: () = {
  "token",
}
```

This code can be rewritten to be not ambiguous, but for larger grammars this is troublesome. Other Parsers(Yacc/Bison) default to shift (and warn) in this [`case`](https://www.gnu.org/software/bison/manual/html_node/Shift_002fReduce.html)

Whats the best way to resolve this with lalrpop?

**Comment by ethanpailes** [comment]
There is an old [comment](https://github.com/lalrpop/lalrpop/issues/67#issuecomment-188951041) that mentions that you can use conditional macros to do this. It links to some [example](https://gist.github.com/nikomatsakis/5fa3bd8291841b853144) code which might be worth looking at.

**Comment by tanin47** [comment]
The example doesn't exactly work, as it can't handle `if else if else if`. We can modify it to handle `else if`but it will have problem down the line with `for` followed by a short `if`.

We can restructure the grammar to handle the no-short-if case explicitly (by duplicating certain rules) as shown here: https://www.cs.cornell.edu/andru/javaspec/19.doc.html

I hope this helps!
