### ISSUE TITLE
Listing all "features" 

### ISSUE THREAD

**Issue by rustonaut** [lalrpop/lalrpop#387]
I think it would be a nice think to have a list of all features with a one sentence description and
a link to a part of the tutorial explaining them.  Or more specific start with the list and
add links once the tutorial covers them.

The reason for this is two fold:

1. features not covered by the tutorial are hard to find or to  know what they are if you 
   stumble across them in the wild
2. the tutorial is a general tutorial, but sometimes this makes it not easy to find the description of an
    specific feature in them

A start could be along the line of:

| name | snipped | description | tutorial |
|---|---|---|---|
| position | `<@L> T <@R>` | uhm, I think it gives the index of the parser in the input | - | 
| error_recovery | `! => { ... }` | recover from parser errors | link | 
| grammar_parameter | `grammar(scale: isize);` | input parameters usable in the generated parser | - | 
| ?? | `Num => func(<i32>)` | maybe automatic number parsing?? | - | 
| custom_error | `"e" =>? ParseError::User { error: "an error" }` | make an action failable | - | 
| custom_macros | `Comma<T> =  { ... }` | allows a non-terminal to be generic about some parameters | link  |
| qunatifier_macros | `<Num?> <Num*> <Num+>` |  a non-terminal which can appear 0..1, 0+, 1+ times | link |
| tuple_macro | `<a:(<Num> ",")*>` | when used with a qunatifier allows crating lists | link |
| extern | `extern { }` | allows to override some parts of the generated parser | - |

Also an extra table for `external`:

| name | snipped | description | tutorial |
|---|---|---|---|
| extern_error | `type Error = MyError;` | sets the error to use in the `ParseError::User` variant | - |
| extern_location | `type Location = MyLoc;` | set the type to for locations instead of `usize` | - |
| extern_tok | `enum Tok { }` | set the type to use for tokens?? | - |

- The idea behind `name` is to have a name to speak about them in issues, name
tests etc.
- The idea of snipped is that if someone sees a unknown feature in the wild he/she
   can likely recognize it based on the snipped
- The description should just give some general idea, it doesn't have to be specific 
  of exhaustive
- Even if some thinks are documented together (e.g. all macro thinks) it's worth listing
   them separately as this can make it easier to recognize what you are looking for

It could be consider to add an additional column if there is a reference documentation
which is with less fluff and example but more exhaustive (e.g. it covers more about the
interaction of `custom_error` and `error_recovery`)

PS: this is not an exhaustive list, missing thinks include e.g. `pub` , `#[inline]`

**Comment by dathinab** [comment]
oh I forgot the short forms 

| name | snipped | description | tutorial |
|---|---|---|---|
| auto_parameters | `<>` | in an action it turns into a list of parameters | link |

**Comment by dathinab** [comment]
oh and there is also that

| name | snipped | description | tutorial |
|---|---|---|---|
| use_lalr | `#[LALR]` | use LALR(1) instead of LR(1) | link |

**Comment by tekknolagi** [comment]
This would be really nice to have. the tuple_macro is really confusing me right now.

**Comment by Storyyeller** [comment]
FYI for anyone else reading this, the `#[LALR]` thing is obsolete. Using it just prints out this warning

```
Warning: Now that the new lane-table algorithm is the default,
         #[lalr] mode has no effect and can be removed.
```

**Comment by chirsz-ever** [comment]
I find `=>@L` and `=>@R` in the source code, what's these meaning?

**Comment by chirsz-ever** [comment]
It seems that you can use `if` in before the action:

```
Enclosed<T>: () = {
    LP <T> RP if T == "a" => (), 
    LB <T> RB => (), 
}

Test: () = Enclosed<"b"> => ();
```

**Comment by trueblablak** [comment]
This is a cheatsheet

**Comment by Pat-Lafon** [comment]
A version of this cheatsheet has been added to the public documentation. Feel free to suggest/improve this page with more issues/prs: http://lalrpop.github.io/lalrpop/cheatsheet.html . Given this, I will be closing this issue. Thanks for the great idea!
