### ISSUE TITLE
Bump minimum required version of petgraph to 0.4.13

### ISSUE THREAD

**Issue by OddBloke** [lalrpop/lalrpop#400]
petgraph below 0.4.12 no longer compiles with rust nightly. Per the [petgraph README](https://github.com/bluss/petgraph), 0.4.13 fixes a conflict with a recently-stabilised method.

(Manually depending on 0.4.13 in my project locally appears to address the compilation issue.)

**Comment by Dylan-DPC** [comment]
@OddBloke thanks for the issue. This is already being taken care of in this [commit](https://github.com/lalrpop/lalrpop/commit/bfa20cd896e703228dea53bca92bd8fa0b8c9ae3).

**Comment by OddBloke** [comment]
Brilliant, thanks!
