### ISSUE TITLE
Escapes in string literals are broken

### ISSUE THREAD

**Issue by jimblandy** [lalrpop/lalrpop#405]
Characters escaped by backslashes are not handled properly in string literals. For example, the following grammar accepts strings of two backslashes, rather than strings of one backslash. There is no way to accept strings of one backslash using LALRPOP's built-in lexical analyzer generator.
```
grammar;

pub Expr: String = {
    <slash: "\\"> => slash.to_owned()
}
```
Internally, `Tokenizer::string_literal` parses that as `Tok::StringLiteral(r#"\\"#)` (in Rust syntax), which eventually makes its way to `lexer::re::parse_literal`, which then tries to escape it again, resulting in the regular expression `r#"\\\\"#`.

**Comment by andersk** [comment]
Works for me.

```rust
mod grammar;

fn main() {
    dbg!(grammar::TestParser::new().parse(r"\"));
}
```

```
[src/main.rs:4] grammar::TestParser::new().parse(r"\") = Ok(
    "\\",
)
```

**Comment by Pat-Lafon** [comment]
This works for me. I am marking this as resolved.
