### ISSUE TITLE
Environment variable 'OUT_DIR' not defined

### ISSUE THREAD

**Issue by Cthutu** [lalrpop/lalrpop#427]
I get this error while following your tutorial:

    error: environment variable `OUT_DIR` not defined
     --> src/main.rs:3:1
      |
    3 | lalrpop_mod!(pub calculator1);
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z     external-macro-backtrace for more info)
    error: couldn't read src/0/calculator1.rs: No such file or directory (os error 2)
     --> src/main.rs:3:1
      |
    3 | lalrpop_mod!(pub calculator1);
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z     external-macro-backtrace for more info)
    
    error: aborting due to 2 previous errors
    
    error: Could not compile `calculator`.
    

Any advice to fix this?

**Comment by Marwes** [comment]
How are you compiling this? `OUT_DIR` should always be set by cargo.

**Comment by Cthutu** [comment]
I am running `cargo test`.  I am running this on Window's Linux Subsystem.   I have the build.rs like this:

    extern crate lalrpop;
    
    fn main() {
        lalrpop::process_root().unwrap();
    }

And main.rs set up like the tutorial (with the unit tests).

**Comment by Cthutu** [comment]
With verbose on I get the additional info:

    Caused by:
      process didn't exit successfully: `rustc --edition=2018 --crate-name calculator src/main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=fdfadf2fcd2d22db -C extra-filename=-fdfadf2fcd2d22db --out-dir /home/matt/calculator/target/debug/deps -C incremental=/home/matt/calculator/target/debug/incremental -L dependency=/home/matt/calculator/target/debug/deps --extern lalrpop_util=/home/matt/calculator/target/debug/deps/liblalrpop_util-a3e1485f682c46b6.rlib --extern regex=/home/matt/calculator/target/debug/deps/libregex-5524183291022439.rlib` (exit code: 1)

**Comment by Cthutu** [comment]
More info: using rustc 1.31.0 (stable)

**Comment by Marwes** [comment]
Are the grammar you are  compiling guarded by `cfg(test)` or in the `tests/` directory? It might be that `OUT_DIR` isn't set in those case but I can't fully remember.

**Comment by Cthutu** [comment]
This is my main.rs:

    #[macro_use]
    extern crate lalrpop_util;
    lalrpop_mod!(pub calculator1);
    
    #[test]
    fn calculator1() {
        assert!(calculator1::TermParser::new().parse("22").is_ok());
        assert!(calculator1::TermParser::new().parse("(22)").is_ok());
        assert!(calculator1::TermParser::new().parse("((((22))))").is_ok());
        assert!(calculator1::TermParser::new().parse("((22))").is_ok());
    }
    
    fn main() {
        println!("Hello, world!");
    }

I can't see how the grammar is guarded by cfg(test).  `cargo build` doesn't work either and produces the same errors.

**Comment by Cthutu** [comment]
I removed the test and it still doesn't build.  I don't know enough about rust to figure this out.

**Comment by Marwes** [comment]
This looks a bit a similar to your issue https://github.com/rust-lang/rust/issues/55897 though it doesn't look like your are importing anything :/

**Comment by Cthutu** [comment]
It is odd, isn't it?

**Comment by Cthutu** [comment]
I tried to build it under my Windows rust setup and still get the same errors.  I've created a github repo with all my files so you can try it yourself: https://github.com/Cthutu/lalrpop_test

**Comment by Cthutu** [comment]
Thanks a lot!  The 0 is probably generated for a default value for OUT_DIR.

**Comment by Firstyear** [comment]
Sorry to necro-post this - I just ran into this myself. Perhaps on https://lalrpop.github.io/lalrpop/tutorial/002_paren_numbers.html you could have an editors note that say "Hey, if you get this error check where your build.rs is". I was on autopilot and accidentally made it in src/build.rs not build.rs so I pretty much did the same. Could be a good little tip to help people if they make the same mistake.
