### ISSUE TITLE
Deprecation warning for trim_left on nightly

### ISSUE THREAD

**Issue by lpil** [lalrpop/lalrpop#428]
```
warning: use of deprecated item 'core::str::<impl str>::trim_left': superseded by `trim_start`
    --> /home/louispilfold/src/gleam/gleam/target/debug/build/gleam-80b0fb72690a65bb/out/grammar.rs:8
452:36
     |
8452 |             let __text = self.text.trim_left();
     |                                    ^^^^^^^^^
     |
     = note: #[warn(deprecated)] on by default
```

Is there a way to disable deprecation warnings on the generated code?

**Comment by lpil** [comment]
Thank you

**Comment by Marwes** [comment]
Since this appears to be code generated by lalrpop itself we should add the attribute automatically for this specific use as well so I will keep this open

**Comment by Badel2** [comment]
Why not just replace `trim_left` with `trim_start`?

**Comment by lpil** [comment]
Wouldn't that mean that lalrpop parsers only compile on nightly?
