### ISSUE TITLE
A more complex example of the lexer

### ISSUE THREAD

**Issue by tanin47** [lalrpop/lalrpop#430]
Hi,

I've been trying to create a custom lexer because I need to detect `\n` in my programming language; everything else is the same. The example about Whitespace is too simple (http://lalrpop.github.io/lalrpop/lexer_tutorial/index.html). 

Specifically, I encountered this exception:

```
error: failed to run custom build command for `lilit v0.1.0 (/home/tanin/projects/lilit)`
process didn't exit successfully: `/home/tanin/projects/lilit/target/debug/build/lilit-7d6b5e7103dec710/build-script-build` (exit code: 1)
--- stdout
processing file `/home/tanin/projects/lilit/src/syntax/lilit.lalrpop`
/home/tanin/projects/lilit/src/syntax/lilit.lalrpop:42:3: 42:9 error: terminal `"class"` does not have a pattern defined for it

--- stderr
    "class" <name:ClassName> "(" <params:Params> ")" <e:ClassExtend?> <methods:Func*> "end" => {
    ~~~~~~~
```

My lexer looks like this:

```
extern {
    type Location = usize;
    type Error = lexer::LexicalError;

    enum lexer::Tok {
        "\n" => lexer::Tok::Linefeed,
        r"[^\n]+" => lexer::Tok::Other
    }
}
```

I guess we cannot use regex right there. But I'm not sure what to do next.

Do you have a more complex example?

Thank you!

**Comment by tanin47** [comment]
@Marwes  I understand the general direction that I need to declare every token. Do you happen to have a more complex (and complete) example that isn't too complex? Because I'm new to both rust and lalrpop. 

Thank you for your explanation, and I'll close this issue.

**Comment by Marwes** [comment]
I have my own parser with a custom leader which might be of help as a reference https://github.com/gluon-lang/gluon/blob/master/parser/src/grammar.lalrpop

**Comment by tanin47** [comment]
This is helpful. Thank you again!

**Comment by evbo** [comment]
For those looking for _a more complex example that isn't too complex_ here are some other great reads:

- [pikelet](https://github.com/brendanzab/pikelet/blob/23ad0c448b495caf028e5e1f405b83c0c69a43fb/src/syntax/parse/lexer.rs): if you want to see a Lalrpop custom lexer in very readable code for a fairly simple grammar
- [json pop](https://github.com/ratmice/json-pop/blob/master/src/lex.rs): if you want to use a super fast external lexer (Logos)
