### ISSUE TITLE
lalrpop_mod! doesn't work in a non-top-level module?

### ISSUE THREAD

**Issue by osa1** [lalrpop/lalrpop#443]
I'm using lalrpop and lalrpop-utils from git. I have a module `foo` inside my crate and I want to put the lalrpop module inside it  (so the full path to the module will be `crate::foo::parser2`). The problem is when I add these lines to `foo/mod.rs`:

```
#[macro_use]
use lalrpop_util;

lalrpop_mod!(pub parser2); // synthesized by LALRPOP
```

I get a `.../out/parser2.rs not found` error. When I do `find . -name parser2.rs` I see that the file is in `.../out/foo/parser2.rs`. I tried using `lalrpop_mod!(pub foo::parser2);` but apparently that's not a valid syntax.

Any ideas on how to make this work?

Thanks

**Comment by Marwes** [comment]
There is a secondary syntax for the macro which lets you specify a path to the grammar https://docs.rs/lalrpop-util/0.16.3/lalrpop_util/macro.lalrpop_mod.html

**Comment by osa1** [comment]
Thanks
