### ISSUE TITLE
Allow #![...] attributes in grammar files (clippy)

### ISSUE THREAD

**Issue by franleplant** [lalrpop/lalrpop#463]
- lalrpop version 0.16.2
- rustc 1.34.0 (91856ed52 2019-04-10)
- cargo 1.34.0 (6789d8a0a 2019-04-01)

Hi! Thanks a lot for this project!
I am currently facing a problem were if I use `clippy` in my project there are pages of clippy errors that come all from the synthesized grammar file.

Clippy's solution to these things is to add an attribute that will make clippy ignore the errors in that file

```rust
#![allow(clippy)]
``` 

But in the lalrpop 16 I try to add said attribute to the top of my grammar `.lalrpop` file and it throws an error.

I notice there is PR open that looks like it addresses this problem https://github.com/lalrpop/lalrpop/pull/384 but it hasn't have much traction since Jan.

I might be able to help fix this if the fix is good enough for my first issue in this repo :)

Thanks!
Fran

**Comment by Marwes** [comment]
If #384 is rebased I would merge it at least. There are some other suggestions in there as well but I think the way it is is probably the simplest fix for it.

The current workaround is to add the attribute inside the macro importing the module.

```rust
lalrpop_mod!(#[allow(clippy)] parser);
```

**Comment by franleplant** [comment]
Hi @Marwes, is it ok if I try to rebase the commits in #384 and just create a new PR to try to make this work?

Additionally, the workaround doesn't work for me, I tried doing it here: https://github.com/franleplant/frd-lisp/blob/master/src/main.rs#L7

(I tried in both lib.rs and main.rs which are the two files that use the parser)

**Comment by Marwes** [comment]
> Hi @Marwes, is it ok if I try to rebase the commits in #384 and just create a new PR to try to make this work?

Sounds good!

Might be that clippy doesn't notice the attribute in that position or something.

**Comment by franleplant** [comment]
Will try to work on this ASAP. Will probably have some time next week.

I've inspected the syntesized file and I don't see the attribute injected
there.

**Comment by jesskfullwood** [comment]
> If #384 is rebased I would merge it at least. There are some other suggestions in there as well but I think the way it is is probably the simplest fix for it.
> 
> The current workaround is to add the attribute inside the macro importing the module.
> 
> ```rust
> lalrpop_mod!(#[allow(clippy)] parser);
> ```

Just to note, this workaround also produces a warning now.
```
warning: lint name `clippy` is deprecated and may not have an effect in the future.
   |
1 | lalrpop_mod!(#[allow(clippy)] parse);
   |                      ^^^^^^ help: change it to: `clippy::all`
```
Unfortunately, the suggested change makes the macro barf.

**Comment by wagenet** [comment]
What's the status on this?

**Comment by wagenet** [comment]
On a recent stable rust, this appears to work for me:
```rs
lalrpop_mod!(
    #[allow(clippy::all)]
    parser
);
```

**Comment by franleplant** [comment]
I can validate that this does not produce any errors with the generated code, although for some reason clippy is still analyzing the synthesized code, is there a way to inspect the generated code?

**Comment by franleplant** [comment]
Ok, I found the build file in `target/debug/build/my_crate-hash/out/parser.rs` and I don't see the added `#[allow(clippy:all)]`, so it looks like the lalrpop is simply ignoring the annotation

**Comment by wagenet** [comment]
@franleplant I have the same versions, so not sure why it wouldn't be working for you. One thing I noticed is that it does need to be `clippy::all` with a double colon.

**Comment by franleplant** [comment]
When you run cargo clippy does it output clippy errors or not?

**Comment by wagenet** [comment]
@franleplant after adding the `#[allow(clippy::all)]` it no longer outputs errors from lalrpop generated code.

**Comment by franleplant** [comment]
Can you see the annotation in the output file? Im going to try again later
(what lalrpop version and rust version are you using?)

**Comment by wagenet** [comment]
@franleplant same lalrpop and rust versions as you.

**Comment by franleplant** [comment]
Hi, Sorry for the delay, I can reproduce this in my toy lisp interpreter: https://github.com/franleplant/frd-lisp/tree/clippy-bug-report

Maybe if you have some time you can download the code and run it? Im using `cargo clippy` to check it.

I notice there are some clippy errors in my code but there are also lots of errors that come out of the synthesized code

**Comment by franleplant** [comment]
Im still seeing the same behavior on lalrpop 19, rust 2018. I tried adding the attribute to lalrpop_module call but no changes, Im still seeing clippy warning for the generated grammar files. Any clues? should I create another bug?

**Comment by franleplant** [comment]
Ok, found the problem, living a summary of what was my problem so that I can hopefully help somebody else:

- My crate is composed of lib and main (lib and binary respectively) where I do all the `lalrporp_mod!` macro call.
- I also was using the generated parser from other file but instead of doing `use crate::parser` I was just simply calling again `lalrpop_mode!` regenerating the grammar for some reason. Once I removed this, together with the comments above, the warnings of the generated code were completely ignored.

So:

- make sure you are calling `lalrpop_mod` macro from your top level files and nowhere else.
- use this form to ignore all the warnings coming from the generated parser

```rust
lalrpop_mod!(
    #[allow(clippy::all)]
    #[allow(unused)]
    pub grammar
);
```

Hope this helps! closing the issue since it was really a problem from my side.

Thanks for all your help

```

**Comment by ccleve** [comment]
The lalrpop_mod!() workaround does not work if you choose the .generate_in_source_tree() option.

How about having a generic way of putting arbitrary text at the top of the generated file? We could do a lot with that.

In my case, I just want to include #![allow(dead_code)] in the file, because it is generating a bunch of warnings like this:

```
warning: associated items `new` and `parse` are never used
    --> src/query/lalrpop/query_parser.rs:2105:16
     |
2104 |     impl Expr0Parser {
     |     ---------------- associated items in this implementation
2105 |         pub fn new() -> Expr0Parser {
     |                ^^^
...
2112 |         pub fn parse<
     |                ^^^^^

```
