### ISSUE TITLE
How to generate rs file by .lalrpop file

### ISSUE THREAD

**Issue by caibirdme** [lalrpop/lalrpop#470]
Hi I'm new here, and I found some confusing areas in the guide book.

I followed the quick start and copied the grammar file:
```
use std::str::FromStr;

grammar;

pub Term: i32 = {
    <n:Num> => n,
    "(" <t:Term> ")" => t,
};

Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();

```
But I don't know how to generate rs file. The book just says:
> Invoking the parser. OK, so we wrote our parser, how do we use it?

I added a build.rs in my project and add `build="build.rs"` in cargo.toml, but when I run `cargo build`, nothing happened
```monkeylang
├── build.rs
├── Cargo.lock
├── Cargo.toml
├── src
│   ├── grammar.lalrpop
│   └── main.rs
└── target
    └── debug

3 directories, 5 files

```
I want to know how to invoke the parser? Or I have to install lalrpop binary?

**Comment by Marwes** [comment]
Chapter 2 should perhaps link back to chapter 1 which explains this http://lalrpop.github.io/lalrpop/tutorial/001_adding_lalrpop.html
