### ISSUE TITLE
Question: is this the limitation of lalrpop or lalr parsing itself?

### ISSUE THREAD

**Issue by tanin47** [lalrpop/lalrpop#475]
Here is a small example:

```
Expr: Expr = {
  "(" <name:"name"> ")" "+" "X" => ... 
  <parent:Parenthesis> "+" "Y" => ...
}

Parenthesis: Expr = {
  "("  <name:"name"> ")" => ...
}
```

The above grammar isn't ambiguous because `X` and `Y` helps with dis-ambiguity.

However, LALRPOP would complain that the grammar is ambiguous because, when reading `) +`, it doesn't know whether to form `"(" <name:"name"> ")"` or `<parent:Parenthesis>`.

I wonder if this is a limitation on LALR(1) parsing itself. Because technically we need to look-ahead for 2 tokens `+` and `X` or `Y` in order to understand the grammar isn't ambiguous.

I understand we can definitely rewrite grammar to avoid 2-token lookahead. But the grammar would become more complex. So, is it possible for lalrpop to handle this case automatically?

**Comment by Marwes** [comment]
```
Expr: Expr = {
  "(" <name:"name"> ")" "+" "X" => ... 
  <parent:Parenthesis> "+" "Y" => ...
}

#[inline]
Parenthesis: Expr = {
  "("  <name:"name"> ")" => ...
}
```

I think adding `#[inline]` would fix the ambiguity in this case.

**Comment by tanin47** [comment]
Yes, `!#[inline]` is what I wanted in order to avoid duplicating the code. Is there an implication on the size/speed of the parser when using `inline`?

**Comment by Marwes** [comment]
I believe the amount of code generated would be equivalent to you writing out the rules explicitly everywhere so there will be some extra code.
