### ISSUE TITLE
Generated source contains `pub`

### ISSUE THREAD

**Issue by ndmitchell** [lalrpop/lalrpop#519]
After generating a grammar with lalrpop 0.18.1 the resulting file contains a number of `pub` entires:

* `pub struct __StateMachine`
* `pub trait __ToTriple`
* `pub enum __Symbol`

These leak into my library API, which isn't great. But worse, because `__Symbol` contains all the AST nodes of my grammar, it forces those nodes to be public too. Should lalrpop only ever use `pub(crate)`? Or is there a configuration to avoid public symbols? I already use `pub(crate) TopLevel: ...` in my definitions.

**Comment by andersk** [comment]
It looks like #584 fixed `__StateMachine` and `__Symbol`.
