### ISSUE TITLE
Unexpected LR error message

### ISSUE THREAD

**Issue by almondtools** [lalrpop/lalrpop#533]
I encountered an unexpected behavior with my grammar for a datalog parser. I reduced it to a smaller grammar/example to make it easier to debug [example.zip](https://github.com/lalrpop/lalrpop/files/4762612/example.zip):

I start with wrong code:
```
q(1;
```
Valid completions at position 3 would be e.g. a `)` or `,X)`  missing. But the error is reporting

```
Unrecognized token `;` found at 3:4
Expected one of ")", "+" or ","
```

If this was right following code should be accepted until pos 4:

```
q(1+;
```

But now the error is:
```
error: Unrecognized token `+` found at 3:4
Expected one of ")" or ","
```

In my real (larger) grammar I could even reproduce errors were the printed expected tokens were a subset of the real expected tokens.

Consequently I tracked down this issue by manually construcing the LR(1)-Automaton. I was surprised that **the automaton was not LR(1)** (on the first view it seems to me some kind or LALR(1) or SLR(1)).

I crawled through the releases and found a release note that `[LALR]` now is deprecated because lane table compression is applied automatically. Switching back to a state without table compression by setting the environment variable `export LALRPOP_LANE_TABLE=disabled` produces the correct error messages.

I read some explanations about [lane tables](http://smallcultfollowing.com/babysteps/blog/2017/03/17/the-lane-table-algorithm/). This algorithm keeps the full power of LR(1) while parsing, but error messages seem to be LALR(1) in the compressed cases. Maybe the correct error message could be reconstructed by processing the states on the stack?

**Comment by almondtools** [comment]
The reproducing project files come here.
[example.zip](https://github.com/lalrpop/lalrpop/files/4756596/example.zip)

**Comment by dburgener** [comment]
This looks like the same issue fixed in https://github.com/lalrpop/lalrpop/pull/737.  Closing.  Please reopen if it's still an issue.
