### ISSUE TITLE
Can I ignore the input after I have successfully matched a rule?

### ISSUE THREAD

**Issue by rehwinkel** [lalrpop/lalrpop#537]
In my parser, I would like to read the input until i have matched my rule exactly once. Any tokens after that should be ignored. Essentially, I want to parse only a part of the source file. Is this at all possible with LALRPOP?

**Comment by Marwes** [comment]
I suppose you could do something like this

```
pub Top: () => {
    <MyRule> =>? {
          Err(ParsedOnce(<>))
    }
};
```

So essentially you accept the rule once then smuggle the output out via a customer error (or by assigning it to an output argument you could add). Then in the caller you check if the `ParsedOnce` error has occured and treat that as success instead (the parser would not be able to return `Ok` even).

**Comment by rehwinkel** [comment]
I now have this rule:
```rs
pub FileImport: Option<Import<'input>> = {
    <import:Import?> =>? {
        Err(lalrpop_util::ParseError::User { error: Error::EndOfInputForImport(import) })
    }
};
```
But the code still produces a regular error about an unrecognized token:
`Err(UnrecognizedToken { token: (87, KwExpose, 93), expected: [] })`

It seems the `=>?` doesn't catch syntax errors. Is there something I'm missing? Or is there another way?

**Comment by Marwes** [comment]
```
pub FileImport: Option<Import<'input>> = {
    <import:Import?> ! =>? {
        Err(lalrpop_util::ParseError::User { error: Error::EndOfInputForImport(import) })
    }
};
```

Add in error recovery after and it should fix that issue at least.

**Comment by Marwes** [comment]
Or add an indirection, which I think will prevent LALRPOP from matching on EOF as it appears to do now

```

FileImport_: Option<Import<'input>> = {
    <import:Import?> =>? {
        Err(lalrpop_util::ParseError::User { error: Error::EndOfInputForImport(import) })
    }
};

pub FileImport: Option<Import<'input>> = {
    FileImport_,
};
```
