### ISSUE TITLE
Tutorial Broken

### ISSUE THREAD

**Issue by HiDefender** [lalrpop/lalrpop#538]
The current release breaks the tutorial. This seems to be a repeat of [513](https://github.com/lalrpop/lalrpop/issues/513).

```
error: failed to run custom build command for `calculator v0.1.0 (~/calculator)`

Caused by:
  process didn't exit successfully: `~/calculator/target/debug/build/calculator-8ea0fd66625d066c/build-script-build` (exit code: 1)
--- stdout
processing file `~/calculator/calculator1.lalrpop`
~/calculator/calculator1.lalrpop:1:1: 1:0 error: The `lexer` feature must be specified unless an `extern` lexer is defined

--- stderr
  use std::str::FromStr;
  ^
```

**Comment by michaeljones** [comment]
I found that frustrating too. The solution seems to be to use: 
```
[build-dependencies]
lalrpop = { version = "0.19", features = ["lexer"] }
```
In your `Cargo.toml`. ie. you need the `lexer` feature enabled.

**Comment by mhdirkse** [comment]
With version 0.19.8 of larlpop, the error messages are different. There are many errors like the following:

```
error[E0432]: unresolved import `self::__lalrpop_util::lexer`
  --> /home/martijn/rust/quadratic-equations-2d/target/debug/build/quadratic-equations-2d-3e9c9d94e3adc760/out/lang.rs:22:31
   |
22 |     use self::__lalrpop_util::lexer::Token;
   |                               ^^^^^ could not find `lexer` in `__lalrpop_util`
```

The proposed fix, adding feature `lexer`, still works.

**Comment by Pat-Lafon** [comment]
The tutorial should be fixed now, open another issue if something comes up.

**Comment by mhdirkse** [comment]
Thanks, @Pat-Lafon. I have a problem with my eyes that prevents me from doing development work. Otherwise I could have checked your work.
