### ISSUE TITLE
heads up, a leading space in a .lalrpop file name generates a rust file with a leading space in the name, which can not be imported

### ISSUE THREAD

**Issue by Nejat** [lalrpop/lalrpop#545]
Hi, while stepping through the Calculator1 tutorial I ran into a strange problem.

Apparently a leading space in a file name is valid, this is first time time I am aware of this. 

To verify, I could not create a new file in Windows Explorer with a leading space or even insert one into an existing file, explorer would just correct it; but, the IDE I am using had no problem creating it ... sigh.

I accidentally created a grammar file with a leading space and the build process picked it up and processed it, generating an rs file with the same leading space; this is logical, but it can not be imported so it breaks things.

The reason I am bringing this to your attention is, I had a very difficult time track down the following error and thought others might experience the same thing.

```error: couldn't read C:\Users\nejat\repos\rust\calculator\target\debug\build\calculator-6be552f3670ffcf2\out/ calculator1.rs: The system cannot find the file specified. (os error 2)```

I could "clearly" see, lol, the file was created, why was it not working!? 
I eventually found the issue, 4K + Aging Eyes are not two things that work well together ;).

Be good

**Comment by Pat-Lafon** [comment]
Hmmm, was looking at this. Technically you can actually use grammar files with leading spaces via `lalrpop_mod!(pub calculator1, "/src/test/ calculator1.rs"); ` but it does seem like something that should be disallowed. Probably more likely to be a bug.

**Comment by Pat-Lafon** [comment]
This should now error in the upcoming release so I am marking this as resolved. Feel free to ping if there was something that was missed.
