### ISSUE TITLE
Tutorial Broken Links

### ISSUE THREAD

**Issue by AlexDikelsky** [lalrpop/lalrpop#546]
In this page http://lalrpop.github.io/lalrpop/tutorial/003_type_inference.html, the links to the code for calculator1 and calculator2 are broken. 

Also, in this page http://lalrpop.github.io/lalrpop/tutorial/004_full_expressions.html, the link to calculator3 is broken.

EDIT: I believe these files are located here right now https://github.com/lalrpop/lalrpop/tree/master/doc/calculator/src

**Comment by Teln0** [comment]
lalrpop.github.io doesn't seem to exist anymore ...

**Comment by Pluriscient** [comment]
> 
> 
> lalrpop.github.io doesn't seem to exist anymore ...

https://lalrpop.github.io/lalrpop/ does so it's more a matter of redirecting to that which is not happening

**Comment by jakevossen5** [comment]
Is this an issue that can be fixed in the `mdbook`, or is there something messed up in the GitHub pages config?

**Comment by maxsnew** [comment]
More broken links here: https://lalrpop.github.io/lalrpop/tutorial/index.html

The link to sub-section 001 is https://lalrpop.github.io/lalrpop/tutorial/tutorial/001_adding_lalrpop.html and should be https://lalrpop.github.io/lalrpop/tutorial/001_adding_lalrpop.html etc

**Comment by bryantbiggs** [comment]
should be resolved with #724 now

**Comment by nikomatsakis** [comment]
Seems to work, indeed.
