### ISSUE TITLE
Confusion about Ambiguous Grammar

### ISSUE THREAD

**Issue by srilman** [lalrpop/lalrpop#552]
I have been writing a parser for a simple calculator that can store variables. For some reason, the parser keeps on throwing an ambiguity error even though it does not seem to be an ambiguous situation. Here is a simple example of the situation:

Grammar:
```rust
use std::str::FromStr;
use crate::ast::{Stmt, Expr, Op};
grammar;


// Main Statements
pub Stmt: Stmt = {
  Expr              ";" => Stmt::Eval(<>),
  <LVal> "=" <Expr> ";" => Stmt::Assign(<>),
};

LVal = { ID, "(" <LVal> ")" };


// Inner Expression
Expr: Box<Expr> = {
  <l:Expr> "+" <r:Term> => Box::new(Expr::Add(l, Op::Add, r)),
  Term
}

Term: Box<Expr> = {
  ID  => Box::new(Expr::Var(<>)),
  Num => Box::new(Expr::Num(<>)),
  "(" <Expr> ")",
};


// Regex Values
ID: String = r"[a-zA-Z][a-zA-Z0-9]*" => <>.to_string();
Num: i32 = r"[0-9]+" => i32::from_str(<>).unwrap();
```

AST
```rust
pub enum Stmt {
  Assign(String, Box<Expr>),
  Eval(Box<Expr>)
}

pub enum Expr {
  Var(String),
  Num(i32),
  Add(Box<Expr>, Box<Expr>),
}
```

When I try building this parser, I receive the following error:
```
Ambiguous grammar detected

    The following symbols can be reduced in two ways:
      "(" ID ")"

    They could be reduced like so:
      "(" ID     ╷ ")"
      │   └─LVal─┘   │
      └─LVal─────────┘

    Alternatively, they could be reduced like so:
      "(" ID     ╷ ")"
      │   ├─Term─┤   │
      │   └─Expr─┘   │
      └─Term─────────┘

    LALRPOP does not yet support ambiguous grammars. See the LALRPOP manual for advice on making your
    grammar unambiguous.
```

From my understanding, a LALR parser generator would be able to determine whether the symbols ` "(" ID ")"` should be reduced to a LVal or Term by performing a lookahead for the assignment operator or the semicolon. Thus, it could differentiate between the two cases and it shouldn't be an ambiguous case. 

Am I forgetting something? If so, what should I do in this case to fix my grammar? BTW I know that LVal (aka surrounding the ID with parens) is kind of pointless right now, but will be useful later, so I cant just remove them entirely. Thanks!

**Comment by Storyyeller** [comment]
An LR(1) parser only uses a single token of lookahead (that's what the 1 in LR(1) means).

Imagine you have input starting with the following: `( ID ) ...`. As soon as the parser hits the `)`, it has to decide whether to reduce the `ID` as a Term or an Lval, using only `)` as the one token of lookahead. Hence the ambiguity.
