### ISSUE TITLE
LALRPOP parsed an incorrect grammar without error

### ISSUE THREAD

**Issue by coriolinus** [lalrpop/lalrpop#566]
I'd accidentally written an [incorrect grammar](https://github.com/coriolinus/adventofcode-2020/blob/7369d05e0941b1dad215f4ff0105695b4e1e8e87/day19/src/parser.lalrpop). The problem is the trailing `.` on [this line](https://github.com/coriolinus/adventofcode-2020/blob/7369d05e0941b1dad215f4ff0105695b4e1e8e87/day19/src/parser.lalrpop#L47). LALRPOP did not flag this grammar as incorrect, but just pasted the action, including the trailing dot, into the generated code. I discovered that the issue was my own error while in the course of what was going to be a different LALRPOP error report.

However, one of the goals of LALRPOP is good error messages. In this case, it didn't raise an error at all; it simply generated (my) incorrect code, which then failed to build. This feels like a case which should raise a LALRPOP error.

**Comment by Pat-Lafon** [comment]
I don't think this is reproducible anymore? I've tried the following grammar and replaced a trailing comma with a period. This raises an error... maybe not the best error, but that's a separate issue. I'll close this issue as completed but can reopen if this is still a live issue.

```rust
use std::str::FromStr;

grammar;

pub Term: i32 = {
    <n:Num> => n,
    "(" <t:Term> ")" => {println!("paren"); t}.
};

Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();
```
