### ISSUE TITLE
Issues with lifetimes while trying to extract string

### ISSUE THREAD

**Issue by magicaltoast** [lalrpop/lalrpop#582]
Hi, I want to extract a regex match and return it as a string pointer but I get a lot oo lifetime problems could anyone explain how I should fix it?

Current errors are `missing lifetime specifier` * 12
But I tried a lot of version of this and no one compiled 

Rust Code
```rust
use lalrpop_util::lalrpop_mod;

lalrpop_mod!(pub grammar);

#[derive(Debug, Eq, PartialEq)]
pub enum Tokens<'a> {
    DirectlyDescending,
    Descending,
    NodeName(&'a str),
}
```
Lalrpop code
```rust
use crate::parser::Tokens;


grammar;


pub Dependency:Tokens = {
    "/" => Tokens::DirectlyDescending,
    "//" => Tokens::Descending
};

pub NodeName: Tokens = < n:r"\w" > => Tokens::NodeName(n);

```
Versions
```
lalrpop = "0.19.4"
lalrpop-util = "0.19.4"
```

**Comment by Marwes** [comment]
You must specify the lifetime in the `Tokens` type.

```
use crate::parser::Tokens;


grammar;


pub Dependency:Tokens<'input> = {
    "/" => Tokens::DirectlyDescending,
    "//" => Tokens::Descending
};

pub NodeName: Tokens<'input> = < n:r"\w" > => Tokens::NodeName(n);

```

**Comment by Schyrsivochter** [comment]
I suggested this yesterday in Gitter, too, but they said they got an error saying that ‘since there is no external token enum specified, the `'input` lifetime is implicit and cannot be declared’ :/

**Comment by Marwes** [comment]
Oh, I guess an external token enum is needed then. See http://lalrpop.github.io/lalrpop/lexer_tutorial/003_token_references.html

**Comment by Schyrsivochter** [comment]
The point is that it *should* be possible to refer to the input lifetime *without* having to define an external lexer.

**Comment by magicaltoast** [comment]
@Marwes So currently there is no option to extract a slice of string without a handwritten lexer?

**Comment by Marwes** [comment]
Not to my knowledge.

**Comment by zoombinis** [comment]
What about a heap-allocated `String`? Can that be parsed? e.g.:

```rust

pub Pin: Pin = <name:"name"> <attrs:Attr<Word>*>  => Pin{<>};

 pub struct Pin {
  pub name: String,
  pub attrs: Vec<String>
}
```
fails with:
>expected struct `String`, found `&str`

**Comment by FranklinChen** [comment]
This issue should be closed. Reference to `'input` in the grammar without an external lexer works fine for me. If there was a limitation, it must have been fixed in the last several months.

**Comment by FranklinChen** [comment]
> What about a heap-allocated `String`? Can that be parsed? e.g.:
> 
> 
> pub Pin: Pin = <name:"name"> <attrs:Attr<Word>*>  => Pin{<>};
> 
>  pub struct Pin {
>   pub name: String,
>   pub attrs: Vec<String>
> }
> fails with:
> 
> > expected struct `String`, found `&str`

You just need to convert to a `String` where desired, e.g. `Pin { name: name.to_owned() ... }`.

**Comment by zoombinis** [comment]
`String` may also be used and a macro can allocate to the heap:
```rust
Heap<T>: String = T => <>.to_string();
```
