### ISSUE TITLE
Allow for `&'static str` in left hand side of production rule?

### ISSUE THREAD

**Issue by jakevossen5** [lalrpop/lalrpop#583]
I basically want to not have to hardcode strings and instead have things be declared in constants that I can change in the future. You can have a `use` that pulls a `const x: &'static str = "example"`, but that can only be used in the right hand side of a production rule. What I really want is to be able to do something like this:

```rust
// in ast.rs
pub const TRUE: &'static str = "true";
pub const FALSE: &'static str = "false";
```
```
// in grammer.lalrpop
use ast::{TRUE, FALSE};

pub boolean: bool = {
    TRUE => true, // first true here refers to the const defined in ast.rs
    FALSE => false,
}
```
This is a bit contrived example, but I hope it is enough to show the value. You can have plain old things in quotes on the left hand side, so I feel like something with the same type shouldn't be too far out there? It would also be nice if we could declare the constants at the top of our lalrpop file.

Let me know what you think.

**Comment by Schyrsivochter** [comment]
You can use LALRPOP nonterminals for that:
```
#[inline] TRUE = "true";
#[inline] FALSE = "false";

pub boolean: bool = {
    TRUE => true, // first true here refers to the const defined in ast.rs
    FALSE => false,
}
```

**Comment by jakevossen5** [comment]
Ah thanks, that works for me!

**Comment by jakevossen5** [comment]
Would you be alright if I submitted a PR to document this in the book? I could make it a new page, unless you think there is a place where you think it will belong better.

**Comment by Schyrsivochter** [comment]
Actually, I’ve found out that there’s an easier way to give terminals a name, using a `match` statement:
```
match {
    "true" => TRUE,
    "false => FALSE,
    _
}
```

**Comment by jakevossen5** [comment]
Yeah, I actually decided to go with that same pattern.

**Comment by zoombinis** [comment]
@Schyrsivochter what goes on the left hand side of your code sample?:

```rust
/* what goes here? */ match {
    "true" => TRUE,
    "false => FALSE,
    _
}
```

**Comment by zoombinis** [comment]
@jakevossen5 @Schyrsivochter what about when you want to avoid _magic strings_ and it just so happens the string you need is already neatly defined in a `struct`:

```rust
pub struct Ast<'input> {
  pub data: &'input str,
}

impl Ast {
  pub const MAGIC: &'static str = "magic_string";
}
```

Unfortunately this won't compile in this case, which is still closely related to OP use case:

```rust
pub boolean: bool = {
    Ast::MAGIC => true,
    "other magick...." => false,
}
```

Is there any way to support this?
