### ISSUE TITLE
please include LICENSE-* files in all published crates

### ISSUE THREAD

**Issue by decathorpe** [lalrpop/lalrpop#600]
The Apache-2.0 and MIT License terms require that the license text is made available with any redistributed sources, which also means that the LICENSE-* files should be included in crates published to crates.io.

To have "cargo publish" pick the files up, adding symlinks `LICENSE-MIT → ../LICENSE-MIT` and `LICENSE-APACHE → ../LICENSE-APACHE` in each of the workspace member directories (at least those that are actually published) is enough, if you're running "cargo publish" from Linux or mac OS (Windows does not really support symlinks, so there actual copies of the files are necessary).

**Comment by Pat-Lafon** [comment]
Does `license.workspace = true` solve this?

**Comment by decathorpe** [comment]
No, that only makes the crate inherit the license in crate metadata, but not the license files themselves.
