### ISSUE TITLE
What does "() => {...}" mean?

### ISSUE THREAD

**Issue by mapleFU** [lalrpop/lalrpop#608]
Hi, when I go through `lalrpop-test`, I found a `inline.lalrpop`:

```
#[test_all]
grammar;

pub E: String = {
    "L" => format!("L"),
    "&" <OPT_L> <E> => format!("& {} {}", <>),
};

#[inline] // without this, it'd be a SR conflict
OPT_L: String = {
    () => format!("()"),
    "L" => format!("L"),
};

```

And I wonder what does `() => ...` means. I have read the document, but I didn't find anywhere explains it.

Does it equal to bison's [empty rules](https://www.gnu.org/software/bison/manual/html_node/Empty-Rules.html) ?

**Comment by Schyrsivochter** [comment]
Yes, exactly. It means a rule that doesn’t consume anything from the input.
