### ISSUE TITLE
Regex escaping is broken

### ISSUE THREAD

**Issue by Volker-Weissmann** [lalrpop/lalrpop#610]
The [rust regex playground](https://2fd.github.io/rust-regex-playground/) claims that `r"\\[a-zA-Z]+"` matches "\\abc", but lalrpop thinks otherwise:
```
match {
    r"\[a-zA-Z]",
    r"\\[a-zA-Z]+",
    r"\\\[a-zA-Z]+",
    r"\\\\[a-zA-Z]+",
}

pub Test: i32 = {
    "\\abc" => 123
};
```
outputs
```
error: terminal `"\\abc"` does not have a match mapping defined for it

  --- stderr
        "\\abc" => 123
```

**Comment by zoombinis** [comment]
@Volker-Weissmann I am new to lalrpop so I might be missing your point, but slightly different grammar works for me in your example:

```rust
pub Test: i32 = {
    r"\\\\[a-zA-Z]+" => 123 // captures "\\abc"
}
```

I interpret your example above as saying _the literal "\\\\abc"_ should map to `123`

**Comment by Volker-Weissmann** [comment]
With your grammar, "\\def" would also map to 123.  I want something like this

```
match {
    r"\[a-zA-Z]",
    r"\\[a-zA-Z]+",
    r"\\\[a-zA-Z]+",
    r"\\\\[a-zA-Z]+",
}

pub Test: i32 = {
    "\\abc" => 123,
    "\\def" => 123
};
```

**Comment by zoombinis** [comment]
@Volker-Weissmann I'm not fully understanding perhaps, but I read your above saying you want \\abc to have higher precedence than \\[a-z...?

Have you seen the `else` statement for defining precedence in the docs? Does that get you any closer?:
https://lalrpop.github.io/lalrpop/lexer_tutorial/001_lexer_gen.html#simple-match-declarations

**Comment by Volker-Weissmann** [comment]
I did some tests with lalrpop's lexer and its consistent, whether a `\\` is used or not.
