### ISSUE TITLE
Allow raw identifiers in grammars

### ISSUE THREAD

**Issue by brendanzab** [lalrpop/lalrpop#613]
Currently the following code:

```rust
pub Term: Term<'arena> = {
    FunTerm,
    <expr: FunTerm> ":" <r#type: Term> => {
        Term::Ann(
            arena.alloc_term(expr),
            arena.alloc_term(r#type),
        )
    },
    ...
};
```

Fails to compile with the following error:

```
.../fathom/experiments/rust-minimal/src/grammar.lalrpop:32:28: 32:28 error: expected string literal; missing `"`?

  --- stderr
        <expr: FunTerm> ":" <r#type: Term> => {
                               ^
```

This is especially troublesome if you use raw identifiers in struct fields, which means you have no way of constructing the struct within the grammar! 😅

**Comment by zoombinis** [comment]
@brendanzab I like your suggestion as it would enable a shortcut for constructing a struct just like `MyStruct{<>}` if all of the names matched in the grammar, but there _is_ at least one work around in the interm by defining an `impl` for `new` in your struct _presuming you can modify your AST code_:

```rust
impl MyStruct {
  pub fn new(surrogate_name: &str) -> Self {
    MyStruct{
      r#type: surrogate_name
    }
  }
}
```

Then in your grammar construct it like:

```rust
// <> contains what was captured as: "surrogate_name"
MyStruct::new(<>)
```

**Comment by kleinesfilmroellchen** [comment]
This also happens with plain `use` at the beginning of files, which the book suggests are just copy-pasted into the generated file.
