### ISSUE TITLE
lalrpop based project fails to compile with Cargo resolver version 2 & edition 2021

### ISSUE THREAD

**Issue by jhinch** [lalrpop/lalrpop#616]
When upgrading a project which uses lalrpop to Cargo resolver v2 or to edition 2021 (where Cargo resolver v2 is the default) you get the following error:

```
error[E0432]: unresolved import `self::__lalrpop_util::lexer`
  --> <REDACTED>/target/debug/build/calculator-455f4b4a27f159ce/out/calculator1.rs:22:31
   |
22 |     use self::__lalrpop_util::lexer::Token;
   |                               ^^^^^ could not find `lexer` in `__lalrpop_util`
```

I reproduced using the calculator project following these two tutorial pages:

* http://lalrpop.github.io/lalrpop/tutorial/001_adding_lalrpop.html
* http://lalrpop.github.io/lalrpop/tutorial/002_paren_numbers.html

with the only modification adding `resolver = "2"` to the `[package]` section

The code compiles correctly with Cargo resolver v1

**Comment by jhinch** [comment]
It seems that this is fixed by enabling the `lexer` feature for the `lalrpop-util` crate. Its not clear if the lexer feature should be enabled by default or the tutorial updated to explicit enable the `lexer` feature.

**Comment by xasopheno** [comment]
> It seems that this is fixed by enabling the `lexer` feature for the `lalrpop-util` crate. Its not clear if the lexer feature should be enabled by default or the tutorial updated to explicit enable the `lexer` feature.

Thank you!

**Comment by errantsky** [comment]
Even though this is supposed to be fixed in #540, I hit the same issue now as I was reading the [online](http://lalrpop.github.io/lalrpop/tutorial/001_adding_lalrpop.html) tutorial.

**Comment by walles** [comment]
> It seems that this is fixed by enabling the `lexer` feature for the `lalrpop-util` crate. Its not clear if the lexer feature should be enabled by default or the tutorial updated to explicit enable the `lexer` feature.

Didn't work for me.

What *did* work was adding `resolver = "1"` to the `[package]` section of `Cargo.toml`.

I rebuilt after that (don't know whether that was needed), then it worked.

**Comment by simnalamburt** [comment]
> It seems that this is fixed by enabling the lexer feature for the lalrpop-util crate. Its not clear if the lexer feature should be enabled by default or the tutorial updated to explicit enable the lexer feature.

It worked for me and I think the tutorial should be updated.

**Comment by Pat-Lafon** [comment]
Closing as completed
