### ISSUE TITLE
Have generated Rust code satisfy Clippy

### ISSUE THREAD

**Issue by FranklinChen** [lalrpop/lalrpop#628]
Related to #614:

I could not find a way to insert Clippy directives into the generated Rust code to shut up thousands of warnings, and had to do the awful thing of adding them to my crate.

It would be nice to either allow `.lalrpop` files to have Clippy directives, or to put them in the generated code. What I have needed to do that should really be in the generated Rust code:

```
#![allow(clippy::just_underscores_and_digits)]
#![allow(unused_imports)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::unused_unit)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]
```

**Comment by Marwes** [comment]
Closed by #632
