### ISSUE TITLE
Facing error `could not compile lalrpop`

### ISSUE THREAD

**Issue by nagarajmanjunath** [lalrpop/lalrpop#635]
Hi all, I am facing the error  ```LLVM ERROR: Broken function found, compilation aborted!
error: could not compile `lalrpop``` when I run ```cargo test```. Using M1 chip macbook_pro

rust version : ```cargo 1.56.0-nightly (b51439fd8 2021-08-09)```.
OS : ```macOS Big Sur V11.6```

**Comment by Pat-Lafon** [comment]
Even if this is reproducible still, it's beyond the scope of lalrpop with how it's generated code gets compiled down to LLVM.
