### ISSUE TITLE
Unexpected error from unused nonterminal

### ISSUE THREAD

**Issue by nicholasbishop** [lalrpop/lalrpop#638]
I'm running into an error when adding a conflicting nonterminal that isn't directly used from the public parser. I'm new to this library, so I'm unsure if this is a real bug or if my mental model of how it works is wrong.

Grammar:
```
grammar;

Identifier: () = {
    r"[a-z]+" => (),
}

pub Field1 = {
    Identifier ":" Identifier
}

Field2 = {
    Identifier ":" "string"
}
```

Parse test:
```rust
fn test() {
    let input = "name: string";
    grammar::Field1Parser::new().parse(input).unwrap();
}
```

Test fails with:
```
UnrecognizedToken { token: (6, Token(2, "string"), 12), expected: ["r#\"[a-z]+\"#"] }'
```

In my mental model of how things are supposed to work, `Field2` shouldn't have any effect on a `Field1Parser`, because `Field1` doesn't reference `Field2` anywhere. However, if I remove `Field2` from the grammar, then this example parses without error.

Here's a repo containing the above example: https://github.com/nicholasbishop/lalrpop-bug. Running `cargo test` reproduces this error.

**Comment by Marwes** [comment]
Lexing is done without taking any context from the parser into account so all tokens you define will be used by the lexer regardless of whether they are used see https://github.com/lalrpop/lalrpop/issues/195

**Comment by nicholasbishop** [comment]
Makes sense, thanks for the explanation and link.
