### ISSUE TITLE
XML parsing for React.js to Solid.js conversion

### ISSUE THREAD

**Issue by rrjanbiah** [lalrpop/lalrpop#655]
LALRPOP is suggested in https://www.reddit.com/r/rust/comments/t37twl/hey_rustaceans_got_an_easy_question_ask_here_92022/hyy26ri/?utm_source=reddit&utm_medium=web2x&context=3 But, can't seem to find any XML parsing. Is that possible or any comments on that?

**Comment by andersk** [comment]
LALRPOP is a parser generator that takes in a grammar and generates a parser. If you want to build an XML parser with it, you need to write an XML grammar.

If you’re looking for an out-of-the-box XML parser, you probably want one of [these crates](https://crates.io/keywords/xml) instead. Also note that JSX is not quite the same as XML—if you want an out-of-the-box JSX parser, it looks like [swc_ecma_parser](https://rustdoc.swc.rs/swc_ecma_parser/) has support for that.

**Comment by rrjanbiah** [comment]
@andersk Thank you

**Comment by Pat-Lafon** [comment]
Thanks for answering @andersk! I'll close this issue
