### ISSUE TITLE
Use reference in __token_to_integer

### ISSUE THREAD

**Issue by Destroyerrrocket** [lalrpop/lalrpop#669]
Hello!
I'm currently writting a parser that requires me to interact with a custom lexer, and for reasons (need to use String) the tokens cannot be Copy-able (They can be Clone-able). In __token_to_integer, you seem to be using "match *{p}token {{", which unfortunately requires a copy. But looking at the function, I see no reason why you wouldn't "match &*{p}token {{" instead. If we could make the change, that would be greatly appreciated!

I'll submit a PR shortly with the change, once I'm done reading the readmes

**Comment by Destroyerrrocket** [comment]
[PR](https://github.com/lalrpop/lalrpop/pull/670) :)

**Comment by Pat-Lafon** [comment]
This was merged in #918. Thanks for starting this push!
