### ISSUE TITLE
Feature request: With custom lexers, allow for terminals to alias to token specializations

### ISSUE THREAD

**Issue by Destroyerrrocket** [lalrpop/lalrpop#671]
I'm truly sorry for the slightly undescriptive title, what I mean is this:
```
extern {
  ...
  enum PreToken {
  ...
    LParen => OperatorPunctuator("("),
    RParen => OperatorPunctuator(")"),
    Comma => OperatorPunctuator(","),
    OperatorPunctuator => OperatorPunctuator(<&'static str>),
  ...
  }
}
```
You'll find that if you test this out, It *kinda* works: It is accepted by the lalrpop parser, and it compiles, but due to line lalrpop/src/normalize/lower/mod.rs:189, with its "all_terminals.sort();", the rules are scrambled up and the match generation does not work. I'm currently working with a version of lalrpop that does not sort the terminals, all tests pass, and I haven't encountered any bugs, but I'd be nice to know if it has some purpose. Also, I'd love for a specialization for the case where "OperatorPunctuator" above has a String, that would make things significantly simpler later on :)

This would be immensely useful, as being able to specialize some of the tokens in my grammars depending on the context I need would aid me a lot for the project I'm working on. In C++ there are things that, depending on the context, may or may not be a token as the preprocessing rules change situation by situation. (for instance, defined is a preprocessing token only when inside of an if preprocessing directive). This would simply make things a lot easier! :D

**Comment by Destroyerrrocket** [comment]
Btw, I think that the best way to allow for easy matching of strings is if you allow for the addition of a conditional to each terminal entry.
You're already generating `"{pattern} if true => Some({index}),"` (at lalrpop/src/lr1/codegen/parse_table.rs:750), so it would be as "easy" as throwing the condition in there. :)
Then I would simply write:
  enum PreToken {
  ...
    Defined => Ident(<String>) => {<>.as_str() == "defined"},
    HasInclude => Ident(<String>) => {<>.as_str() == "__has_include"}
    Ident => Ident(<String>),
...
  }

**Comment by osa1** [comment]
> I'm currently working with a version of lalrpop that does not sort the terminals, all tests pass, and I haven't encountered any bugs, but I'd be nice to know if it has some purpose.

I don't think sorting is necessary, it's probably just there to help with debugging (maybe generated code looks nicer). In my LR(1) parser generator I don't re-order token declarations and [your example works][1].

I just tried removing that `sort` line in lalrpop and all the tests pass. It should be OK to remove it.

> Btw, I think that the best way to allow for easy matching of strings is if you allow for the addition of a conditional to each terminal entry.

I think this should be possible. As you figured out, the right-hand sides in those `enum` alternatives give the patterns to be used when checking the next terminal (token). It should be possible to allow `if ...` part there.

[1]: https://github.com/osa1/parsegen/blob/74422e5b38cfcfd25ae219a1b2226b9d446d6bb3/tests/tests.rs#L672-L695

**Comment by Destroyerrrocket** [comment]
> I think this should be possible. As you figured out, the right-hand sides in those enum alternatives give the patterns to be used when checking the next terminal (token). It should be possible to allow if ... part there.

Yeah! I'd be really happy if it got implemented :)

**Comment by dburgener** [comment]
This should be good now, with #918 merged.

**Comment by Destroyerrrocket** [comment]
Thank you for your work!
