### ISSUE TITLE
cannot find ast.rs

### ISSUE THREAD

**Issue by nablabla** [lalrpop/lalrpop#679]
Hi, I have it done like in the tutorial, my structure is: three files in src/ (ast.rs, grammar.lalrpop and main.rs)
and it cives me this error:
error[E0432]: unresolved import `crate::ast`
   --> [..]\parser\target\debug\build\parser-93fe4303c1cd0c8c\out/grammar.rs:622:16
    |
622 |     use crate::ast::{Expr, Opcode};
    |                ^^^ could not find `ast` in the crate root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `parser` due to 3 previous errors

I don't get it

**Comment by osa1** [comment]
Could you paste the contents of your files?

Did you forget to declare the ast module in `main.rs` maybe?

**Comment by nablabla** [comment]
I get it now. I was new to rust and everything.
In the grammar file at the top, there need to be the imports in a way such that they work properly after generating the parser.rs file to the output folder, which is a folder like this "\target\debug\build\parser-93fe4303c1cd0c8c\out\grammar.rs"
in my case "crate::parser::ast::{Stmt,  Expr, OpCode};
This can depend on where you have your grammar, and on whether you build a library or a binary(application)
