### ISSUE TITLE
Exclude word from lexer

### ISSUE THREAD

**Issue by Gregofi** [lalrpop/lalrpop#680]
Hello, is there some possibility to exclude word from lexer? For example `r"[a-zA-Z][a-zA-Z]*" ~ "define" => IDENTIFIER`, which would match all words except the word `"define"`.

I tried using negative look-ahead, which seems to not be supported.

Thanks for any help!

**Comment by sigmasoldi3r** [comment]
Sorry for necrobumping this issue but, is there any resources related to that matter? I'm looking somewhat to have negative lookbehind or just "do not match this" type thing, and it may be present in docs, but I'm missing it.

**Comment by chanbengz** [comment]
AFAIK, Logos (an external lexer) can control the precedence, as you may need. But the drawback is that you have to follow LALRPOP's procedure to collaborate with an external lexer, as documented.

**Comment by sigmasoldi3r** [comment]
> If you define a non regex symbol in your lexer (like the word "define" in the example above), it will take precedence over any regex that also matches. So in other words if both "define" and "[a-z]" are in your grammar, then the "[a-z]" pattern will omit "define" because it was matched by a different pattern at higher precedence.
> 
> You can also of course write a more complicated regex that excludes certain patterns directly in the regex.
> 
> If all else fails, handling special casing in your action code or writing a custom lexer are the ultimate fallbacks.

Interesting, them my ambiguity problem may not be in the lexing part, which makes me even more confused hehe.
