### ISSUE TITLE
Release a new version and yank last release

### ISSUE THREAD

**Issue by youknowone** [lalrpop/lalrpop#778]
Edit: 0.19.11 is released without any of this changes. Those will be included in 0.20

bugs
- [x] #773
  - suggested fix is #774
- [x] #775 
  - suggested fix is #776 

0.20
- [x] #777

Rather than revert and re-revert, I'd like to suggest to create a `0.x` branch and backport only version fixes including #775. (or the speedup one if desired)

**Comment by nikomatsakis** [comment]
@youknowone agreed about creating the branch. What a pain.

**Comment by youknowone** [comment]
Another idea. Yank last one and release new one as 0.20
If we care about backward compatibilty, 0.19 expects only a single patch about cargo fix about regex

**Comment by youknowone** [comment]
#777 is desired to be 0.20. Then regex problem will be clearly fixed.

**Comment by youknowone** [comment]
yanked 0.19.10 and released 0.19.11
