### ISSUE TITLE
Adding a feature `unicode`

### ISSUE THREAD

**Issue by youknowone** [lalrpop/lalrpop#789]
The problem happens because it cames from user side and lalrpop doesn't know users use what kind of features of regex.

- The feature will turn on `regex/unicode` and `regex-syntax/unicode`.
- The feature will be a default feature.

This will let lalrpop users can use any unicode regex when they want but can reduce dependency down they don't need one.

Does this make sense?

**Comment by jannic** [comment]
That sounds like a good idea.
Users of `lalrpop` don't need to know that it internally uses the `regex` crate, it's perfectly possible to only have a dependency on `lalrpop`.
Having to add a direct dependency on `regex` and `regex-syntax` just to enable some optional dependencies on them is not intuitive. But a `unicode` feature on `lalrpop` is. It's also easy do document: If you use unicode character classes in your grammar, you need to add the `unicode`-feature on `lalrpop`.

**Comment by youknowone** [comment]
see also https://github.com/lalrpop/lalrpop/issues/750#issuecomment-1528762984

Thanks @jannic

**Comment by nikomatsakis** [comment]
This makes sense to me, though I would appreciate from somebody a summary of exactly what this breakage is all about.

**Comment by youknowone** [comment]
@nikomatsakis by looking #750, user can input any regex. Here is my guess based on it.

Until regex 1.7, even if your input required unicode feature of regex-syntax, it passed because lalrpop implicitly had dependency to regex-syntax with unicode feature.
With regex 1.8, it is broken. regex 1.8 requires regex-syntax 0.7 while lalrpop depends on regex-syntax 0.6. Our dependency to regex(implicitly 1.8) enabled regex-syntax 0.7 with unicode feature, but regex-syntax 0.6 with no feature. Because lalrpop itself didn't require the feature, we couldn't catch the problem. 
Users who depending on regex-syntax with unicode features started to experience problem because unicode feature is unexpectedly and silently dropped in their dependency.

**Comment by dburgener** [comment]
> Because lalrpop itself didn't require the feature, we couldn't catch the problem.

Small clarification, lalrpop does require this feature in CI (for example [here](https://github.com/lalrpop/lalrpop/blob/4eb985ec90192a91fdb5913bb78750ad90ae29a9/lalrpop-test/src/comments.lalrpop#L5), however because CI is ran with a Cargo.lock present, we never ran lalrpop CI with regex 1.8.  Lalrpop binary users get the versions in lalrpop's Cargo.lock, but lalrpop library users do now.

Other than that, I think your explanation is spot on.
