### ISSUE TITLE
Custom lexer needs context information from the parser?

### ISSUE THREAD

**Issue by mccolljr** [lalrpop/lalrpop#802]
This might be related to #195?

I want to parse a grammar where the same sequence of characters can mean different things in different contexts. The custom lexer I am using can handle this, but I can't tell it which mode to use from the grammar

#### Example:

- A (custom) lexer understands the individual token `">"`.
- Inside an expression context, `">" ">"` should parse as the right-shift operator, but `">" SPACE+ ">"` should parse as the `>` operator followed by an error indicating that `">"` is not a valid start token for the right-side expression.
- Outside of an expression context, `">" ">"` and `">" SPACE+ ">"` should both parse to two consecutive closing `>` braces.

The lexer can't decide between emitting two `">"` tokens or a single `">>"` token without some hint from the parser.

I can see two possible solutions:
1. Write my grammar in such a way that whitespace is a named token and explicitly encoded in the rules
2. Inform the lexer that it should NOT generate `">>"` right-shift tokens outside of an expression context

I'm currently using the option 1, but the downside is that I have to manually place whitespace productions all over the grammar, then manually filter `SPACE`, `SPACE_OR_NEWLINE`, etc out of error messages.

It would be nice to have the ability to do something like option 2. Ideally, I would have the ability to modify the lexer state when entering/exiting certain rules so I could push and pop `LexMode` values from a stack, informing the lexer which tokens it may legally generate in that context. I could definitely be wrong, but it doesn't seem like there's a way to accomplish this via lalrpop right now.

Is there a way to accomplish this, or something like it, with the current version lalrpop?

**Comment by youknowone** [comment]
I had similar problem with soft keywords processing.

**Comment by mccolljr** [comment]
As I continu to work on this grammar, I am realizing that the "explicit whitespace" approach fails. A grammar that is LR(1) when whitespace is implicit can become non-LR(1) when whitespace is explicit. An example of this:

This grammar is LR(1) (whitespace does not generate tokens)
```
ListOfBounds: ... = { ... }

NameWithBounds: ... = {
 <l:@L> <name:Name> <r:@R> => ...,
 <l:@L> <name:Name> ":" <bounds:ListOfBounds> => ...,
}

ListOfNamesWithBounds: Vec<ast::NameWithBounds> = {
  "(" <mut list:(<NameWithBounds> ",")> <NameWithBounds> ")" => ...
}
```

This grammar is not LR(1) (whitespace generates tokens)
```
ListOfBounds: ... = { ... }

NameWithBounds: ... = {
 <l:@L> <name:Name> <r:@R> => ...,
 <l:@L> <name:Name> SPACE* ":" SPACE* <bounds:ListOfBounds> => ...,
}

ListOfNamesWithBounds: Vec<...> = {
  "(" <mut list:(SPACE* <NameWithBounds> SPACE* ",")> SPACE* <NameWithBounds> SPACE* ")" => ...
}
```

The second grammar fails when disambiguating the two cases in `NameWithBounds` because a single token lookahead can yield a `SPACE` token, but either a `":"` or `","` token is required to know which path to take.

**Comment by nikomatsakis** [comment]
It would be nice to have feedback from the parser to the lexer, but it would require some significant planning because of how LR parsers work.

**Comment by mccolljr** [comment]
@nikomatsakis Understood, I think my main question at this point is how I might be able to "work around" this issue. I have adjusted my custom lexer to generate a structure of the form:

```rust
struct Token<'s> {
  pub kind: TokenKind,       // this is an int enum
  pub lit: &'s str,          // this is a str slice from the source
  pub leading_space: bool,   // true if the lexer matched some whitespace before this
  pub leading_newline: bool, // true if the lexer matched at least one newline before this
}
```

This gives me information about whitespace in a way that I can examine in rule code, while avoiding generating whitespace tokens that make the grammar non-LR(1). I wasn't sure how to
use a structure like this in the definitions for tokens in a lalrpop grammar file, though -
I've opted for a hand-written recursive descent parser for the time being. Even if I could
do that, is there a way to communicate to the parser code that a rule "did not match after all"? I believe this approach would still need something like this to disambiguate the case where
two consecutive tokens only *actually* match if there is no whitespace between them.

**Comment by youknowone** [comment]
RustPython has context-aware lexer. https://github.com/RustPython/Parser/blob/40a603208f40f6aa904297fa1dbd7c6d4ba5125a/parser/src/soft_keywords.rs#L46-L54
It could be simpler if lexer can take state of parser.

**Comment by mccolljr** [comment]
Thanks @yannham and @youknowone for the examples - unfortunately it doesn't look like either approach will work in my situation. Unless I am misunderstanding, these approaches both assume the lexer can somehow derive enough context to choose a mode on its own, which is unfortunately not possible in my case

**Comment by Pat-Lafon** [comment]
We now have documented a way for this to be possible. I'll close this as completed. See that pr #916 for more details and note the related issues that are linked.
