### ISSUE TITLE
Custom lexer with custom Token type

### ISSUE THREAD

**Issue by ethindp** [lalrpop/lalrpop#803]
I was looking through the custom Lexer tutorial, but I'm not really sure how to use the lexer I've written with Lalrpop. In particular, the regular expressions I use are ones that the Regex crate does not (and most likely will not) support; I instead use fancy_regex for those features. However, my Lexer returns types like this:

```rust
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum Token {
    Identifier {
        line: usize,
        column: usize,
        value: String,
    },
// ...
```

(It also returns an `anyhow::Result<Vec<Token>>`.) What would be the (correct) way of incorporating this lexer into a Lalrpop grammar? (I just have a standalone `tokenize` function, though I can change that to a full `Lexer` type if that's required.)

**Comment by ethindp** [comment]
@arnaudgolfouse I've made some significant changes to my lexer; notably, I've moved the line and column data to a struct, so that tokens look like this:
```rust
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Token {
    pub line: usize,
    pub column: usize,
    pub data: TokenData,
}
```

And then I just have a discriminated enumeration for each token data type:

```rust
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum TokenData {
    /// Whitespace denotes a set of characters utilized to create separation between textual elements, such as words and symbols.
    Whitespace(char),
    /// Identifiers are used as names.
    Identifier(String),
    /// An integer literal is a numeric literal in the conventional notation (that is, it solely consists of an integer in any base, but it is not a significand).
    IntegerLiteral(IBig),
    /// A real literal is a floating-point literal: it can be in any valid base and it consists of a significand and exponent.
    RealLiteral(f64),
    /// A character literal is formed by enclosing a graphic character between two apostrophe characters.
    CharacterLiteral(char),
    /// A string literal is formed by a sequence of graphic characters (possibly none) enclosed between two quotation marks used as string brackets. They are used to represent operator symbols, values of a string type, and array subaggregates.
    StringLiteral(String),
    /// A comment starts with two adjacent hyphens and extends up to the end of the line.
    Comment(String),
    // Eof marks the end of file
    Eof,
    // Reserved words
    // ...
    // Delimiters
    // ...
```

I think that this might make writing the parser with Lalrpop a lot easier. I do have a couple questions about what you wrote:

1. Why do I need to redefine the Token enum? Presumably my Lexer already defines this, so it seems redundant.
2. Why do something like `"IDENT" => Token::...`? What does this accomplish?

**Comment by arnaudgolfouse** [comment]
I did not design this library, so someone more knowledgable than me might correct me !

1. If you are referring to the `enum Token { ... }` in the `extern` block, it doesn't _really_ redefine the Token enum. Instead, it maps each variant to a separate integer (`fn __token_to_integer` in the generated file). This is used to generate the parsing tables, and so it needs to know how many variants there are/where they appear in the grammar, which it cannot do if Token is just an arbitrary type you pull from somewhere else.
2. From what I understand the design of LALRPOP is that productions are written as follow:
    ```lalrpop
    Assign = {
        "IDENT" "=" Expr => /* */,
    }
    ```
    But if you supply your own lexer, lalrpop does not know what "IDENT" or "=" refer to, and so we need to tell it that this refers to `Token::Identifier(<String>)` and `Token::EqualSign` (or similar). And so we have to write the `"IDENT" => Token::...` part.

**Comment by yannham** [comment]
I didn't take part in the original design either, but I believe what @arnaudgolfouse just said is correct. The `enum Token` isn't a definition but a mapping, from symbols that LALRPOP understands in the grammar as terminals, to a Rust enum variants representing your token.

We could probably imagine a different mechanism, maybe something based on traits with a `derive` macro and custom attributes acting directly on the definition of the `Token` enum, keeping everything in one place?

**Comment by ethindp** [comment]
@yannham and @arnaudgolfouse I'm still kind of confused but maybe seeing the generated code would help me understand things. Just to clarify, if I want to make the mapping using the current way I do things, I should create a `Lexer` type, implement [Iterator](https://doc.rust-lang.org/std/iter/trait.Iterator.html), and then define an extern block like so:

```rust
extern {
    type Location = (usize, usize); // line, column
    type error = Anyhow::Error;

    enum Token {
        "ident" => TokenData::Identifier(id),
        // ...
    }
}
```
And that's it? Then I just pass in my lexer as well as an input?

**Comment by yannham** [comment]
@ethindp yes, that should be it! Note that your iterator mutn't produce just tokens but "spanned tokens", that is `Result<(Location, Token, Location), Error>`.

**Comment by yannham** [comment]
@ethindp is your initial solved? Could we consider closing this issue?

**Comment by ethindp** [comment]
Yes, thank you!
