### ISSUE TITLE
Dangling symlinks anywhere in the crate cause obscure build failures

### ISSUE THREAD

**Issue by legeana** [lalrpop/lalrpop#808]
How to reproduce:
1. Create a new crate with `build.rs` file `fn main() { lalrpop::process_root().unwrap() }`
2. Create a dangling symlink: `ln -sf /file/does/not/exist dangling-symlink`
3. Run `cargo build`:

```shell
$ cargo build
   Compiling cargo-dangling-symlinks v0.1.0 (/home/liri/cargo-dangling-symlinks)
error: failed to run custom build command for `cargo-dangling-symlinks v0.1.0 (/home/liri/cargo-dangling-symlinks)`

Caused by:
  process didn't exit successfully: `/home/liri/cargo-dangling-symlinks/target/debug/build/cargo-dangling-symlinks-6e4fe4fd1c3bb576/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:2:29
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Full crate example: https://github.com/legeana/lalrpop-dangling-symlinks

This was quite frustrating to debug as the error message is extremely obscure. I had to resort to `strace -f target/.../build-script-build` to determine what file lalrpop was trying to open.

I believe lalrpop should do two things:
1. Improve error messages by indicating the path that doesn't exist.
2. Ignore dangling symlinks.

**Comment by yannham** [comment]
Hi! Thanks for reporting. I personally have little time currently to dive in new issues on LALRPOP, but I would be happy to review and merge any PR fixing this.
