### ISSUE TITLE
Is it supposed to be possible to use the lexer generator without enabling the unicode feature?

### ISSUE THREAD

**Issue by analog-hors** [lalrpop/lalrpop#810]
Issue #750 mentioned that the `lexer` feature requires unicode support on the regex crate due to it unconditionally generating regexes that require it. That issue was resolved by #786, which added the `unicode` feature to enable unicode support. However, `lexer` does not imply `unicode`, despite the fact that `unicode` is still always required to use `lexer`.

Is it supposed to be possible to use the lexer generator without enabling the `unicode` feature?
- If so, support for this case is broken due to the lexer generator unconditionally generating regexes that require `unicode`
- If not, the `unicode` feature is redundant, and should probably be implied by `lexer`

**Comment by yannham** [comment]
On paper, I would be tempted to say that the lexer generator _should_ be usable without enabling the unicode feature, but I might be missing something here. What do you think @nikomatsakis @youknowone ?

**Comment by Pat-Lafon** [comment]
@dburgener See #814 `Set an ASCII skip rule when "unicode" feature is disabled. Purely an ergonomic improvement.` because of https://github.com/lalrpop/lalrpop/blob/1ad22327659369a1e4b0ef5815472615b365d4dd/lalrpop/src/lexer/intern_token/mod.rs#L62 which regex defaults to being unicode-aware

**Comment by dburgener** [comment]
Ah, interesting.  Seems like that is disabled if users specify an ignore pattern (which I do in the repo I was testing on).

If that's the only way the default lexer doesn't respect the unicode feature, then #814 should address this, right?

**Comment by Pat-Lafon** [comment]
I believe so

**Comment by dburgener** [comment]
This can be closed now that #829 has merged, I think?

**Comment by youknowone** [comment]
I expect #829 closes this issue. If the problem was not fixed, please open the issue again. Thank you!
