### ISSUE TITLE
Assertion instead of error message

### ISSUE THREAD

**Issue by fabi321** [lalrpop/lalrpop#811]
When using a macro without any arguments, an assertion is triggered:
https://github.com/lalrpop/lalrpop/blob/master/lalrpop/src/normalize/prevalidate/mod.rs#L381

Example:
```
grammar;
Macro<Smth>: String = {
    Smth => <>.to_string()
}

pub Root: String = {
    Macro<>
}
```
This definition triggers the assertion, instead of raising an error message. Changing it to `Macro<"a">` fixes it.
Version: 0.20.0

**Comment by Pat-Lafon** [comment]
Is https://github.com/Pat-Lafon/lalrpop/commit/23ee8f7eab9de1fddcbf6227a69782634d7c93a6 all that's needed to fix this?

**Comment by fabi321** [comment]
looks fine

```
  processing file `~/tmp-lalrpop/src/tmp.lalrpop`
  ~/tmp-lalrpop/src/tmp.lalrpop:7:5: 7:11 error: macros must have atleast one argument

  --- stderr
        Macro<>
        ~~~~~~~
```

**Comment by Pat-Lafon** [comment]
@fabi321 This issue can be closed now?
