### ISSUE TITLE
Grouping rules together

### ISSUE THREAD

**Issue by ManicMarrc** [lalrpop/lalrpop#837]
I need to parse the else-branch of an if statement, and to do that, I tried to use this rule:

```rust
Expr: ast::Expr = {
  <start:@L>
    "if" <condition:Expr> <bstart:@L> <block:Block> <bend:@L>
    ("else" <estart:@L> <else_:Block> <eend:@L>)?
  <end:@L> =>
    ast::Expr::If {
      condition: Box::new(condition),
      block,
      block_span: bstart..bend,
      else_,
      else_span: estart.map(|estart| estart..eend.unwrap()),
      span: start..end,
    },
}
```

But all I get is this error:
```error: named symbols like `estart:@L` are only allowed at the top-level of a nonterminal```

**Comment by dburgener** [comment]
The "()?" grouping makes the contained symbols be "not at the top-level", which as the error says is disallowed.

The clean way to do this is define a Terminal for your else block:

```
#[inline]
ElseBlock = {
    "else" <estart:@L> <else_:Block> <eend:@L>
}

Expr = 
    if <condition> <block> <ElseBlock>?
```

That way the contents of the elseblock are at the top level.  The reason why this approach is better (and required by lalrpop) is that when we define ElseBlock as an inlined non-terminal, we have to give a type to the contents.  Your code above assumes that the ? returns (Option<Range>, Option<Block>, Option<Range>).  That makes ergonomic sense in this case, but "Option<(Range, Block, Range)>" is probably actually a more sensible return type (for one thing, one "?" maps to one Option, but more significantly, the three Options in the first case, really should be all Some() or None together, and it's desirable that the typing reflect that), and that's pretty unergonomic.  When you define ElseBlock yourself, you get to determine what type it should have, and get an Option<Whatever you want> in your Expr rule.
