### ISSUE TITLE
How can I parse newline-separated code with lalrpop?

### ISSUE THREAD

**Issue by abiriadev** [lalrpop/lalrpop#850]
I am building a parser for a scripting language where each line is delimited by a newline, as opposed to the traditional semicolon(you can think of languages like Python or Lua). To handle newline as tokens, I've created an external lexer:

```rs
extern {
	type Location = usize;
	type Error = LexError;

	enum Token {
		// ...
		"\n" => Token::NewLine,
		// ...
	}
}
```

After that, I came up with the following grammar:

```rs
pub Code: Code = Separated<Expr, "\n"+> => Code(<>);
```

However, the problem is that I want the parser to handle expressions spanning multiple lines as well. This means it should ignore newlines between every rule, except the `Code` rule mentioned above. Ideally, it should be possible as `"\n"* <every rule> "\n"*`.

Unfortunately, the rule conflicts when implemented in this way. Moreover, replicating the same code for every rule doesn't seem efficient(It should be handled by a lexer, but I can't simply ignore newline at the lexer level as I previously mentioned).

Does anyone have suggestions or similar experience with me? I appreciate any guidance in advance.

**Comment by hypotrochoid** [comment]
In my own parsers, I add this match at the beginning of the grammar-
```match {
    r"[ \t\r]*" => { }, // ignore space and tab and cr
    r"\{\n*" => BlockStart, // Don't make newline into EOL after {
    r"\}" => BlockEnd, // Make newline into EOL except after {
    r"\n[ \t\n]*" => EOL, // Make newline into EOL except after {
...```

then I can explicitly match on the `EOL` nonterminal in the grammar.

**Comment by abiriadev** [comment]
Thanks! This seems like a possible solution!
