### ISSUE TITLE
Update (external library) lexer example for Logos 0.13+

### ISSUE THREAD

**Issue by airstrike** [lalrpop/lalrpop#869]
[Since 0.13](https://github.com/maciejhirsz/logos/releases/tag/v0.13), Logos no longer requires the `#[error]` variant, yet the example in the tutorial still uses it:

https://github.com/lalrpop/lalrpop/blob/0b244afd19f6da8f5c095e8c780a48f80abe21bf/doc/src/lexer_tutorial/005_external_lib.md?plain=1#L94-L100

**Comment by Pat-Lafon** [comment]
This got addressed in #874
