### ISSUE TITLE
Default lexer edge case

### ISSUE THREAD

**Issue by timurnkey** [lalrpop/lalrpop#873]
I'm running into an issue with what I assume is the lexer. I'm using the [documentation here](https://lalrpop.github.io/lalrpop/tutorial/006_macros.html) to produce a vector.

```
Term: Box<Expr> = {
    Ident => Box::new(Expr::Ident(<>)),
    Literal => Box::new(Expr::Literal(<>)),
    "[" <WithCommas<Term>> "]" => Box::new(Expr::List(<>)),
    "(" <Expr> ")",
}

WithCommas<T>: Vec<T> = {
    <mut v:(<T> ",")*> <e:T?> => match e {
        None => v,
        Some(e) => {
            v.push(e);
            v
        }
    }
};
```

Works:
- `['a']`// strings seem fine
- `['a']`// strings seem fine w/ optional trailing comma
- `[0,]` // optional trailing comma
- `[ 0]` // whitespace prefix
- `[0 ]` // whitespace suffix
- `[(0)]` // parentheses work too 
- `[0,1]` // comma separated values work fine

Does not work:
- `[0]`

I'm currently locked into Rust v1.63, so this is the version I'm using. I haven't tested whether or not this works as expected on the latest version.
```
[dependencies]
lalrpop-util = { version = "0.19.9", features = ["lexer", "std"], default-features = false }
lalrpop = { version = "0.19.9", features = ["lexer"], default-features = false, optional = true }
```

edit - whoops forgot the error!
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError("Unrecognized token `[0]` found at 0:3\nExpected one of \"!\", \"(\", \"-\", \"0\", \"[\", \"activity\", \"approvers\", \"eth.tx\", \"false\", \"private_key\", \"true\", \"wallet\", r#\"'[^'\\\\n]*'\"#, r#\"[1-9]+[0-9]*\"# or r#\"[a-zA-Z][_a-zA-Z0-9]*\"#")', policy/examples/tester.rs:25:45
```

**Comment by dburgener** [comment]
Thanks for the report!

Would you be able to share the full grammar you're using (or even better, a simplified complete working example to repro the error)?  The "unrecognized token" error is likely lexer related, but without seeing your Terminal definitions, it's hard to tell what's going on.

**Comment by timurnkey** [comment]
Thanks for the reminder to pare it down. I was able to identify the issue. I can't seem to find a way to support both of these cases:
- a list with a single integer element: `[0]`
- a list access operator: `[1,2,3][0]`

Here's [the code](https://github.com/timurnkey/lexer-test/tree/main) if you'd like to take a look. The initial commit shows a baseline with the full grammar while HEAD shows the minimal case to repro this issue.

**Comment by timurnkey** [comment]
I found something interesting based on the code above^. Given these two test cases:
```
cargo run --example parse "[0]"
cargo run --example parse "[1]"
```

If I modify my `Expr` declaration to remove `AccessOp`, both of the test cases fail:
```
pub Expr: Box<Expr> = {
-   <left:Expr> <op:AccessOp> => Box::new(Expr::Access(left, op)),
     Term,
 };
```

However, the tests both pass if I also remove the `AccessOp` declaration:
```
-AccessOp: AccessOp = {
-    r"\[[0-9]+\]" =>? {
-        let parts = &<>[1..(<>.len() - 1)];
-        let index = parts.parse::<u32>().map_err(|e| ParseError::User{
-            error: "unable to parse access operation to u32",
-        })?;
-
-        Ok(AccessOp::Index(index))
-    },
-};
```

This feels like unexpected behavior since `AccessOp` is no longer a part of the `Expr` declaration, but I'd love your thoughts.

**Comment by timurnkey** [comment]
I was able to resolve this issue. Thanks for maintaining this awesome project!
