### ISSUE TITLE
Please add a option to not skip whitespaces

### ISSUE THREAD

**Issue by EricDeng1001** [lalrpop/lalrpop#879]
I know a lot have mentioned this, but I saw no solution for now. And I think keep whitespaces really matters when writing some language that need to capture user's input as is.  So I put an issue here just to remind to add this option.

**Comment by davidhs** [comment]
I think you can use the whitespace tokens in your grammar. If you take a look the LALRPOP book in section 6.1 LALRPOP's lexer generator, in the sections Renaming match declarations and Customizing skipping between tokens you can see how you include whitespace tokens in your grammar.

**Comment by dburgener** [comment]
davidhs's solution should work.  I'm closing this, please reopen if you think that something is still missing.
