### ISSUE TITLE
warning: unexpected `cfg` condition name: `rustfmt`

### ISSUE THREAD

**Issue by asomers** [lalrpop/lalrpop#892]
The latest rustc compiler tries to detect the use of unknown `#[cfg()]` conditions.  It's triggering in lalrpop-generated code.  The easiest way to reproduce the problem is to simply run `cargo check -p nobol` in lalrpop's own git repo.  Or, it can be reproduced by trying to compile a file like this:
```
grammar;

pub Num: i16 = r"[0-9]+" => i16::from_str(<>).unwrap();
```
Which results in the warning
```
warning: unexpected `cfg` condition name: `rustfmt`
  --> /usr/home/somers/src/rust/bfffs/target/debug/build/bfffs-555042f4e29eb538/out/x.rs:12:12
   |
12 | #[cfg_attr(rustfmt, rustfmt_skip)]
   |            ^^^^^^^
   |
   = help: consider using a Cargo feature instead or adding `println!("cargo::rustc-check-cfg=cfg(rustfmt)");` to the top of the `build.rs`
   = note: see <https://doc.rust-lang.org/nightly/cargo/reference/build-scripts.html#rustc-check-cfg> for more information about checking conditional configuration

warning: unexpected `cfg` condition name: `rustfmt`
   --> /usr/home/somers/src/rust/bfffs/target/debug/build/bfffs-555042f4e29eb538/out/x.rs:303:12
    |
303 | #[cfg_attr(rustfmt, rustfmt_skip)]
    |            ^^^^^^^
    |
    = help: consider using a Cargo feature instead or adding `println!("cargo::rustc-check-cfg=cfg(rustfmt)");` to the top of the `build.rs`
    = note: see <https://doc.rust-lang.org/nightly/cargo/reference/build-scripts.html#rustc-check-cfg> for more information about checking conditional configuration
```
This is the rust version I'm currently using:
```
> rustc --version -v
rustc 1.80.0-nightly (e82c861d7 2024-05-04)
binary: rustc
commit-hash: e82c861d7e5ecd766cb0dab0bf622445dec999dc
commit-date: 2024-05-04
host: x86_64-unknown-freebsd
release: 1.80.0-nightly
LLVM version: 18.1.4
```

**Comment by Pat-Lafon** [comment]
This just landed on nightly right? I'm interested in fixing this(I think it exposed some other cfg issues that went undetected with `cfg(feature = "test")`. Ironically though, the example you included has just been fixed on the latest nightly(because of issues with rustfmt).

**Comment by asomers** [comment]
Yeah, it only started to fail sometime within the last few weeks.

**Comment by dburgener** [comment]
I think this has been fixed on nightly and doesn't require changes to lalrpop.  Building on nightly current works fine with no warnings.  I'm going to close this.  Feel free to reopen if you still see something needing fixing.
