### ISSUE TITLE
Guards in pattern matching?

### ISSUE THREAD

**Issue by OJarrisonn** [lalrpop/lalrpop#921]
Are there any guards syntax for lalrpop yet? When parsing identifiers for a programming language how to filter-out keywords?

**Comment by dburgener** [comment]
> Are there any guards syntax for lalrpop yet?

Guards are supported in macro statements, unfortunately there isn't any documentation or particularly good examples for it yet.  The only example I'm aware of is this grammar in a test case: https://github.com/lalrpop/lalrpop/blob/d700700a5c32d31871067111b51ae86ed2a479b7/lalrpop/src/normalize/macro_expand/test.rs#L62-L73

Can you share a little more about your use case?  I looked briefly into writing some documentation for this last week, but wasn't sure what a good tangible use case would be to use as a motivating example in the docs.

> When parsing identifiers for a programming language how to filter-out keywords?

Normally people handle this at the lexer level.  If you have a terminal `r"[a-z]+"` and another terminal `"keyword"`, then the lexer will always match the more specific `"keyword"` if possible, even though that also matches the regex.  So something like

```
Identifier: String = {
    r"[a-z]+";
}
```

should match only strings that aren't explicit tokens elsewhere in the grammar, which typically your keywords are.

**Comment by OJarrisonn** [comment]
In my use case i have a list of keywords `KEYWORDS` and my identifiers rule is:

```rs
Identifier: Identifier = {
    <i:r"[a-z][a-z0-9_]*"> => Identifier(v.to_string())
}
```

I wish i could add a guard like `if !KEYWORDS.contains(v)` before the `=>` just like any `match` expression

**Comment by dburgener** [comment]
Are the keywords in `KEYWORDS` listed in your grammar anywhere?  If so, they'll be picked up as tokens by the lexer, and therefore won't match the regex in Identifier at all.

To make it concrete, if in addition to what you wrote if you also have:

```
Val: Val = {
    "val" Identifier Type "=" Number
}
```

Then symbols like "val" are lexed as different tokens than the `r"[a-z][a-z0-9_]*"` regex, and so the Identifier rule won't match on the string "val" at all, which seems to achieve your high level goal.

**Comment by OJarrisonn** [comment]
Oh so that's the default behaviour? Is this in the docs? If so, my bad

**Comment by dburgener** [comment]
Yep, documented here: https://lalrpop.github.io/lalrpop/lexer_tutorial/001_lexer_gen.html#precedence-of-fixed-strings

Glad I was able to get you pointed in the right direction.
