### ISSUE TITLE
Warning for unreachable empty type

### ISSUE THREAD

**Issue by dburgener** [lalrpop/lalrpop#936]
Building with latest nightly I get:

```
warning: unreachable pattern
    --> /home/dburgener/lalrpop/target/debug/build/whitespace-aff48bae6bdd1300/out/parser.rs:2567:13
     |
2567 |             Err(error) => Err(__lalrpop_util::ParseError::User { error }),
     |             ^^^^^^^^^^ matches no values because `LexicalError` is uninhabited
     |
     = note: to learn more about uninhabited types, see https://doc.rust-lang.org/nomicon/exotic-sizes.html#empty-types
     = note: `#[warn(unreachable_patterns)]` on by default

warning: `whitespace` (lib) generated 1 warning
```

The new rust behavior was introduced here: https://github.com/rust-lang/rust/pull/122792

What's notable is that the correct code won't actually be valid until 1.82.  Here's the generated code:

```
impl<> __ToTriple<> for Result<(usize, lexer::Tok, usize), lexer::LexicalError>
{
    fn to_triple(value: Self) -> Result<(usize,lexer::Tok,usize), __lalrpop_util::ParseError<usize, lexer::Tok, lexer::LexicalError>> {
        match value {
            Ok(v) => Ok(v),
            Err(error) => Err(__lalrpop_util::ParseError::User { error }),
        }
    }
}
```

To fix it, we need to switch to an `if let` pattern that only matches the Ok variant, since the Error variant is unreachable due to whitespace defining an empty enum for LexicalError (see the docs for explanation: https://lalrpop.github.io/lalrpop/lexer_tutorial/003_writing_custom_lexer.html).  The problem is that the `if let` is illegal in 1.81 in earlier, since 1.81 doesn't understand that the error variant is unreachable.  So the code to fix the warning requires a 1.82 MSRV.

We are of course far from the only project affected and there's a discussion in an issue on the rust github about it: https://github.com/rust-lang/rust/issues/129031.

My opinion is that we should hold off on addressing this warning for a few weeks to see where the community goes in terms of the backwards compatibility/migration path.

This is all setting aside the fact that this being interplay between user-written and generated code makes things fairly complicated in our case.  Quite possibly we'll just want to `#[allow(unreachable_patterns)]` in the relevant part of the generated code unconditionally to address this regardless, and that is backwards compatible.  But we might as well see if the above issue has a resolution first, since we still have some time until the warning hits stable.

**Comment by Pat-Lafon** [comment]
Yeah we can wait to see what happens. Alternatively, does this still lint if we use [Result::map_err](https://doc.rust-lang.org/std/result/enum.Result.html#method.map_err) which seems to be what this code is doing?

**Comment by dburgener** [comment]
> Alternatively, does this still lint if we use [Result::map_err](https://doc.rust-lang.org/std/result/enum.Result.html#method.map_err) which seems to be what this code is doing?

Good suggestion!  It does not.  That's better code anyways, besides dodging the problem.  PR coming in a few minutes.

**Comment by Pat-Lafon** [comment]
Yeah, lets wait to see what happens.
