### ISSUE TITLE
Balanced tokens, like html

### ISSUE THREAD

**Issue by galaxor** [lalrpop/lalrpop#942]
How can I express the idea of the same token appearing twice, and I don't care what it is, but it does need to be the same.

I'm talking about a situation like HTML, where you have `<tag></tag>`.

Or, a language that contained strings like:

AA
ABBA
ABCCBA

How could I parse that, without naming every possible symbol?

**Comment by dburgener** [comment]
I would do this by checking in action code.  Something like

```
grammar(errors: &mut Vec<ErrorRecovery<usize, Token<'input>, String>);

Sym: String = {
    r"[a-zA-Z]"
};

OpenTag: String = {
    "<" <Sym> ">" => <>
};

CloseTag: String = {
    "<" "/" <Sym> ">" => <>
};

Expr = {
    <open: OpenTag> <e: Expr> <close: CloseTag> =>? {
        if open != close {
             return Err(ParseError::User {
                  error: "Unmatched tags"
             }
        }
        Ok(e)
    },
    Sym
};
```

Not compile checked, so probably contains syntax errors, but hopefully communicates the high level idea.

**Comment by dburgener** [comment]
Hopefully the above answered your question.  I'm going to go ahead and close this for now.  Feel free to reopen if needed.
