### ISSUE TITLE
Error Recovery not working when encountering a lexical error with Logos

### ISSUE THREAD

**Issue by chanbengz** [lalrpop/lalrpop#992]
Trying to build a compiler with lalrpop and Logos and play with error recovery following [error recovery](https://lalrpop.github.io/lalrpop/tutorial/008_error_recovery.html) and [external lib](https://lalrpop.github.io/lalrpop/lexer_tutorial/005_external_lib.html)

```rust
use logos::{Logos, FilterResult};
// ...

#[derive(Default, Debug, Clone, PartialEq)]
pub enum LexicalError {
    InvalidInteger(String),
    InvalidCharacter(String),
    InvalidString(String),
    UnexpectedEndOfProgram,
    NonAsciiCharacter,
    #[default]
    UnknownToken
}

#[derive(Debug, Logos, PartialEq, Clone)]
#[logos(error = LexicalError)]
#[logos(skip r"[ \t\r\n\f]+")]
pub enum Token {
    #[end]
    EndOfProgram,

    // Operators
    #[token(">")]
    OpGreaterThan,
    // ...
}
```

```rust
use lexer::tokens::{Token, LexicalError};
use ast::tree;
use lalrpop_util::ErrorRecovery;

grammar<'err>(errors: &'err mut Vec<ErrorRecovery<usize, Token, LexicalError>>);

extern {
  type Location = usize;
  type Error = LexicalError;

  enum Token {
    "identifier" => Token::Identifier(<String>),
  // ...
  }
}

pub CompExpr: Box<tree::CompExpr> = {
    #[precedence(level="1")]
    Term,
   // ...
}

Term: Box<tree::CompExpr> = {
    <n: "int"> => Box::new(tree::CompExpr::Value(tree::Value::Integer(n))),
    "(" <CompExpr> ")",
    ! => { errors.push(<>); Box::new(tree::CompExpr::Error) },
}
```

And test with 
```rust
let mut errors = Vec::new();
let lexer = lexer::lexer::Lexer::new("1 + $"); // Invalid token '$'
let parser = CompExprParser::new();
assert_eq!(format!("{}", parser.parse(&mut errors, lexer).unwrap()), "1 + Error");
```

however it returns
```
---- tests::test_error_recovery stdout ----
thread 'tests::test_error_recovery' panicked at src/parser/src/lib.rs:86:38:
called `Result::unwrap()` on an `Err` value: User { error: UnknownToken }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_error_recovery
```

Could this issue be solved? Or should I remove the `UnknownToken` and match any invalid tokens?

BTW, I'm new to lalrpop and wondering how can I match some specific error syntax as in Yacc/Bison, for example

```yacc
Json:
      Value
    ;
Value:
      Object 
    | Array
    | STRING
    | NUMBER
    | NUMBER NUMBER error { puts("Numbers cannot have leading zeroes, recovered"); }
    | TRUE
    | FALSE
    | VNULL
    | Array RB error { puts("Extra close, recovered"); }
    ;
```

**Comment by dburgener** [comment]
The parser will return an `Err` variant if it hits EOF before successfully recovering.  I suspect that's what happened here, but it's hard to tell because you skipped the parts of the grammar that might make this successfully parse (eg I don't see any handling of "+" anywhere, and it's not clear what the other variants of CompExpr besides Term are).

As a first debugging step, I suggest adding [`log_debug()`](https://docs.rs/lalrpop/latest/lalrpop/struct.Configuration.html#method.log_debug) to your `Configuration` at build time and you'll get some detailed messages on what error recovery was up to.

**Comment by chanbengz** [comment]
The grammar is the same as that in [tutorial](https://lalrpop.github.io/lalrpop/lexer_tutorial/005_external_lib.html). I'll try on `log_debug()` once I'm back to keyboard. Thanks a lot for the suggestion.

**Comment by dburgener** [comment]
> The grammar is the same as that in tutorial

The snippets you posted aren't though.  Is your `CompExpr` supposed to match the tutorial's `Expression`?  I see that you defined an `OpGreaterThan` that isn't in the tutorial.  My concern is that it kind of looks like you've rewritten the tutorial a bit to do comparison operators instead of arithmetic operators, but you're testing with `+` in the test code.  Is `+` a valid character in this grammar?  Is it valid at the parser level in a `CompExpr`?

**Comment by chanbengz** [comment]
>  I see that you defined an OpGreaterThan that isn't in the tutorial. My concern is that it kind of looks like you've rewritten the tutorial a bit to do comparison operators instead of arithmetic operators, but you're testing with + in the test code. Is + a valid character in this grammar? Is it valid at the parser level in a CompExpr?

Ah, sorry for the confusion. I predefined a list of token (`+` is in it) for further implementation but for now `OpGreaterThan` doesn't appear in grammar.

**Comment by chanbengz** [comment]
Well, I've tried `log_debug()` with the codes in [doc](https://github.com/lalrpop/lalrpop/tree/master/doc/lexer) and then put `ErrorRecovery` into it, with codes in [gist](https://gist.github.com/chanbengz/f88c682efa680059fbd5fba51847d385). But it didn't seem much different in output message. 

```bash
# with log_debug()
➜  cal cargo run
   Compiling cal v0.1.0 (~/Downloads/cal)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.15s
     Running `target/debug/cal`
Err(User { error: InvalidToken })

# with log_info()
➜  cal cargo run
   Compiling cal v0.1.0 (~/Downloads/cal)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/cal`
Err(User { error: InvalidToken })
```

The configuration in `build.rs`. I can't see any issue here.

```rs
fn main() {
    // lalrpop::process_src().unwrap();
    lalrpop::Configuration::new()
        .log_debug()
        .process_current_dir().unwrap();
}
```

Oh, my friends mentioned that, it might be something related to the `Error` defined in `extern` block

```rs
extern {
  type Location = usize;
  type Error = LexicalError;
  // ...
}
```

cause there's no such code in the example of `ErrorRecovery` in [tutorial](https://lalrpop.github.io/lalrpop/tutorial/008_error_recovery.html). If it could possibly be the cause, how am I supposed to deal with error recovery?

**Comment by chanbengz** [comment]
Tested also with the internal lexer in [calculator7](https://github.com/lalrpop/lalrpop/tree/master/doc/calculator) with `1 + $`, and it emits

```bash
---- calculator7 stdout ----
thread 'calculator7' panicked at src/main.rs:168:10:
called `Result::unwrap()` on an `Err` value: InvalidToken { location: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Perhaps I wrongly blamed the external lexer. My guess is that lexical error is considered to be an "external error" that would never handled as `ParseError` in ErrorRecovery.

**Comment by chanbengz** [comment]
> Oh, my friend mentioned that, it might be something related to the `Error` defined in `extern` block

Somehow my friend got it right. His "hypothesis" was that lalrpop parser expected a valid `Ok((usize, Token, usize))` from the input stream `Result<(usize, Token, usize), LexicalError>`, while making exception immediately encountering the `Err(LexicalError)`. This will make it hard to perform error recovery because the token stream has not yet entered the grammar parser and exited itself. 

```rust
pub type Spanned<Tok, Loc, Error> = Result<(Loc, Tok, Loc), Error>;

pub struct Lexer<'input> {
  // instead of an iterator over characters, we have a token iterator
  token_stream: SpannedIter<'input, Token>,
}
```

In the tutorial example of using Logos as lexer, I we need to reformat the output of the lexer stream. Logos returns a `Result<Token, LexicalError>` in our case. Therefore if token is not a valid `Ok(Token)` but a `Err(LexicalError)`, the `token?` will recognize it.

```rust
impl<'input> Iterator for Lexer<'input> {
  type Item = Spanned<Token, usize, LexicalError>;

  fn next(&mut self) -> Option<Self::Item> {
    self.token_stream
      .next()
      .map(|(token, span)| Ok((span.start, token?, span.end)))
  }
}
```

Since the parser dislikes the `Err(LexicalError)`, I did a little trick here to solve my issue.

```rust
impl<'input> Iterator for Lexer<'input> {
  type Item = Spanned<Token, usize, LexicalError>;

  fn next(&mut self) -> Option<Self::Item> {
    self.token_stream
      .next()
      .map(|(token, span)|
        match token {
          Ok(token) => Ok((span.start, token, span.end)),
          Err(_) => Ok((span.start, Token::Error, span.end)), // or specify your lexical error to parse error
        }
      )
  }
}
```

and in `tokens.rs` and `*.lalrpop`, put the `Token::Error` (`Token::Error` is a `Token`, just like NaN is a number in Javascript) 

```rust
// grammar.lalr
extern {
  type Location = usize;
  type Error = LexicalError;

  enum Token {
    // ...
    "error" => Token::Error,
  }
}

// token.rs
pub enum Token {
  // ...
  Error,
}
```

And for test scripts

```plaintext
var a = 42;
var b = 23;

print (a - ); # missing term
print (a - $); # invalid token
```

it returns

```bash
Ok([Variable { name: "a", value: Integer(42) }, Variable { name: "b", value: Integer(23) }, Print { value: BinaryOperation { lhs: Variable("a"), operator: Sub, rhs: Error } }, Print { value: BinaryOperation { lhs: Variable("a"), operator: Sub, rhs: Error } }])

# Error Recovery
[ErrorRecovery { error: UnrecognizedToken { token: (48, RParen, 49), expected: ["\"identifier\"", "\"int\"", "\"(\""] }, dropped_tokens: [] }, ErrorRecovery { error: UnrecognizedToken { token: (62, Error, 63), expected: ["\"identifier\"", "\"int\"", "\"(\""] }, dropped_tokens: [(62, Error, 63)] }]
```

which is exactly what I need! I guess my issue is done here. 

Should I make some modification to add as tips in [doc](https://lalrpop.github.io/lalrpop), like in chaptrer `Tutorial` or `Controlling the lexer`? I'm not sure whether my solution is elegant enough.

Could it be solved inside lalrpop, like handling the `LexicalError` in error recovery? That would be a good feature I guess :)

**Comment by dburgener** [comment]
Thanks for the thorough investigation!

I'm looking at the lalrpop-util code around this, and yes, I think I see in the code matching your experience - on a lexer error, the parser exits with an error immediately without attempting error recovery, while on a parser error it first attempts error recovery.

It looks fairly fixable, and I agree that having error recovery for lexer errors would be good.  Let me take a stab at that, and if no surprises crop up, we can probably fix this in lalrpop so the workaround isn't necessary.  If it turns out that there's some reason why we can't fix this in lalrpop, we'd definitely want to document the workaround, but I don't currently see any reason we can't fix it on the lalrpop side.

**Comment by chanbengz** [comment]
> Thanks for the thorough investigation!

It's no big deal. I barely proposed my problem from an user's perspective, and I haven't yet taken a look at lalrpop's source.

Thanks a lot for the responsive reply! I'm willing to help if there's anything I can do.
