### ISSUE TITLE
Our CI has a non-deterministic test

### ISSUE THREAD

**Issue by dburgener** [lalrpop/lalrpop#994]
I'm having a little trouble reproducing it. Apparently that test case does some random testing? https://github.com/lalrpop/lalrpop/blob/ab154926da43fbbb9107bd374cef4159aff1fa4c/lalrpop/src/lr1/build/test.rs#L167

I'm interested in random testing in general, but it might not be great to have it in CI.

There might even be a comment about this failure mode? https://github.com/lalrpop/lalrpop/blob/ab154926da43fbbb9107bd374cef4159aff1fa4c/lalrpop/src/generate.rs#L13-L27

Since the call stack was exceeded, we didn't get a printout.

_Originally posted by @Pat-Lafon in https://github.com/lalrpop/lalrpop/issues/993#issuecomment-2484091509_

**Comment by Pat-Lafon** [comment]
I see in the git blame that there is even a commit lowering this enumeration depth most likely because the previous maintainer hit a similar issue. https://github.com/lalrpop/lalrpop/commit/e932f811a6598a70b93c917fc3ada9e7a5a303c6

My guess is that the limit is still too high for the ci systems that you occasionally get unlucky?

**Comment by dburgener** [comment]
> My guess is that the limit is still too high for the ci systems that you occasionally get unlucky?

Yeah, that makes sense.

I think we should make the test deterministic by seeding the rng, and then add some additional iterations to get broader coverage since it will run the same thing every time.  That way any failures will be deterministic.  It would be nice to do some offline runs with with previously untested seeds for broader coverage like a fuzzer would do, but that requires some way to identify "interesting" seeds so that those can get added to the regression suite, and I'm not sure how far down that road we want to run.  Something like `cargo fuzz` needs to treat your code as more of a black box, and I don't think supports running on unit tests on private functions like this - primarily because of the need to instrument code coverage.

In terms of seeding the rng, the existing rng seems to not support manual seeding (https://rust-random.github.io/rand/rand/rngs/struct.ThreadRng.html), so we'd want to switch out to one of the other rngs supported by `rand` if we want to go the seeding route.
